export const DEPARTMENTS = [
  "EHS",
  "Purchase and Store",
  "Production",
  "Operation",
  "Maintenance",
  "Maintenance - Automation",
  "Maintenance - Electrical",
  "Utility",
  "Admin",
  "HR",
  "Accounts & Finance",
  "Die Shop",
  "Design & Engineering",
  "Metallurgy & LAB",
  "Forging",
  "Heat Treatment",
  "IT & Infrastructure",
  "Quality",
];

export const LOCATIONS = [
  "Security Gate 1",
  "Security Gate 2",
  "Security Gate 3",
  "Propane Yard",
  "ETP & STP",
  "Forging Shop",
  "Machine Shop",
  "Utility 1",
  "Utility 2",
  "Hazardous Store",
  "Scrap Yard",
  "MRS Room",
  "EB Room",
  "110 KV Sub Station",
];

export const HAZARDS = [
  "Corrosive Chemicals",
  "Flammables",
  "Explosives",
  "Hot Materials",
  "Steam",
  "Compressed Gas",
  "Fumes Dust",
  "High/Low Pressure",
  "High/Low Temperature",
  "Live/Dead Electrical",
  "Overhead Danger",
  "Radiation Source",
  "Moving Machine",
  "Open Rotating Parts",
  "Traffic",
  "Confined Space",
  "Use of Ladder",
  "Use of Scaffold",
  "Roof Condition Slippery",
  "Floor Condition Slip Trip",
  "Hidden Cables",
  "Leaky Pipelines",
  "Buried Pipelines",
  "Suspended Load",
  "Biological Hazards",
  "Fall from Height",
  "Others",
];

export const PPE_LIST = [
  "Helmet",
  "Safety Shoes",
  "Gum Boots",
  "Hand Gloves Cotton",
  "Hand Gloves Cut Resistant",
  "Hand Gloves PU",
  "Hand Gloves Electrical",
  "Hand Gloves Nitrile",
  "Hand Gloves Leather",
  "Apron",
  "PVC Overall",
  "Ear Plug/Ear Muff",
  "Dust/Gas Mask",
  "Breathing Apparatus",
  "Full Body Safety Harness",
  "Safety Net",
  "Crawling Boards",
  "Others",
];

export const CHECKLIST_BY_TYPE: Record<string, string[]> = {
  HotWork: [
    "Combustibles Removed",
    "Sparks Isolated",
    "Explosion Test Done",
    "Fire Fighting Equipment Provided",
    "Welding Sets Earthed",
    "Welding Cables Good Condition",
    "Adequate Ventilation for Fumes",
    "Welding Holder Good Condition",
    "Gas Cutting Checked",
    "Others",
  ],
  HeightWork: [
    "Ladder Checked",
    "Scaffold Checked and Tagged",
    "Safety Harness Provided",
    "Safety Net Installed",
    "Lifeline Installed",
    "Access Route Cleared",
    "Barricade Below",
    "Medical Test for Workmen",
    "Supervision Provided",
    "Others",
  ],
  ConfinedSpace: [
    "Service Process Isolated",
    "Electrical Isolated",
    "Vessel Cleared",
    "Air Ventilation Adequate",
    "Forced Draft Provided",
    "Oxygen Level Checked",
    "Toxic Gas Checked",
    "Explosive Atmosphere Checked",
    "24V Hand Lamp Provided",
    "Men Inside with Safety Harness",
    "Men Inside with Lifeline",
    "Rescue Team Outside",
    "Others",
  ],
  default: [
    "Job Site Checked",
    "Area Cordoned Off",
    "Caution Board Displayed",
    "Portable Tools Checked",
    "PPE Provided",
    "Lifting Tools Certified",
    "Supervision Provided",
    "Others",
  ],
};

export const ELECTRICAL_ISOLATION_OPTIONS = [
  "Fuse Removed",
  "Isolated and Locked",
  "Put Off and Locked",
  "Tested Non Operative",
  "Others",
];

export const SERVICE_ISOLATION_OPTIONS = [
  "Depressurised",
  "Valve Closed and Tagged",
  "Line Blank",
  "Line Disconnected",
  "Material Drained",
  "Flushed",
  "Others",
];

export const PERMIT_TYPE_LABELS = {
  HotWork: "Hot Work",
  ColdWork: "Cold Work",
  ConfinedSpace: "Confined Space",
  HeightWork: "Height Work",
  ElectricalWork: "Electrical Work",
  Excavation: "Excavation",
  Lifting: "Lifting",
  Shutdown: "Shutdown",
  ChemicalHandling: "Chemical Handling",
  GeneralWork: "General Work",
} as const;

export const STATUS_LABELS = {
  Draft: "Draft",
  Submitted: "Submitted",
  HODReview: "HOD Review",
  AreaReview: "Area Review",
  IsolationReview: "Isolation Review",
  SafetyReview: "Safety Review",
  FinalApproval: "Final Approval",
  Approved: "Approved",
  Active: "Active",
  Suspended: "Suspended",
  Rejected: "Rejected",
  Closed: "Closed",
  Expired: "Expired",
} as const;

export const STATUS_COLORS = {
  Draft: "bg-slate-700/60 text-slate-300 border-slate-600",
  Submitted: "bg-blue-900/60 text-blue-300 border-blue-700",
  HODReview: "bg-amber-900/60 text-amber-300 border-amber-700",
  AreaReview: "bg-amber-900/60 text-amber-300 border-amber-700",
  IsolationReview: "bg-orange-900/60 text-orange-300 border-orange-700",
  SafetyReview: "bg-purple-900/60 text-purple-300 border-purple-700",
  FinalApproval: "bg-indigo-900/60 text-indigo-300 border-indigo-700",
  Approved: "bg-green-900/60 text-green-300 border-green-700",
  Active: "bg-green-900/80 text-green-200 border-green-600",
  Suspended: "bg-yellow-900/60 text-yellow-300 border-yellow-700",
  Rejected: "bg-red-900/60 text-red-300 border-red-700",
  Closed: "bg-slate-800/60 text-slate-400 border-slate-600",
  Expired: "bg-orange-900/60 text-orange-400 border-orange-700",
} as const;

export const RISK_COLORS = {
  Low: "bg-green-900/60 text-green-300 border-green-700",
  Medium: "bg-amber-900/60 text-amber-300 border-amber-700",
  High: "bg-orange-900/60 text-orange-300 border-orange-700",
  Critical: "bg-red-900/80 text-red-200 border-red-600",
} as const;

export const PENDING_STATUSES = [
  "Submitted",
  "HODReview",
  "AreaReview",
  "IsolationReview",
  "SafetyReview",
  "FinalApproval",
] as const;
