/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const AirEmissionSource = IDL.Variant({
  'Stack' : IDL.Null,
  'Vehicle' : IDL.Null,
  'Fugitive' : IDL.Null,
});
export const AirPollutant = IDL.Variant({
  'CO2' : IDL.Null,
  'NOx' : IDL.Null,
  'SOx' : IDL.Null,
  'VOC' : IDL.Null,
  'PM10' : IDL.Null,
});
export const AddAirEmissionInput = IDL.Record({
  'value' : IDL.Float64,
  'source' : AirEmissionSource,
  'unit' : IDL.Text,
  'pollutant' : AirPollutant,
  'measurementDate' : IDL.Text,
  'department' : IDL.Text,
  'regulatoryLimit' : IDL.Float64,
});
export const CarbonScope = IDL.Variant({
  'Scope1' : IDL.Null,
  'Scope2' : IDL.Null,
  'Scope3' : IDL.Null,
});
export const AddCarbonInput = IDL.Record({
  'month' : IDL.Nat,
  'co2eTonnes' : IDL.Float64,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'scope' : CarbonScope,
});
export const InductionStatus = IDL.Variant({
  'Fail' : IDL.Null,
  'Pass' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ContractorEmployee = IDL.Record({
  'trade' : IDL.Text,
  'inductionStatus' : InductionStatus,
  'inductionDate' : IDL.Opt(IDL.Text),
  'idNumber' : IDL.Text,
  'empName' : IDL.Text,
  'certificateNumber' : IDL.Opt(IDL.Text),
});
export const EffluentParameter = IDL.Variant({
  'PH' : IDL.Null,
  'BOD' : IDL.Null,
  'COD' : IDL.Null,
  'TSS' : IDL.Null,
  'HeavyMetals' : IDL.Null,
});
export const EffluentType = IDL.Variant({
  'Domestic' : IDL.Null,
  'Stormwater' : IDL.Null,
  'Process' : IDL.Null,
});
export const AddEffluentInput = IDL.Record({
  'samplingDate' : IDL.Text,
  'value' : IDL.Float64,
  'parameter' : EffluentParameter,
  'effluentType' : EffluentType,
  'department' : IDL.Text,
  'regulatoryLimit' : IDL.Float64,
});
export const EmploymentType = IDL.Variant({
  'Contract' : IDL.Null,
  'FullTime' : IDL.Null,
  'Temporary' : IDL.Null,
});
export const AddEmployeeInput = IDL.Record({
  'contact' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'designation' : IDL.Text,
  'site' : IDL.Text,
  'joiningDate' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'employmentType' : EmploymentType,
  'department' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const EmployeeStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
  'Resigned' : IDL.Null,
});
export const EmployeeView = IDL.Record({
  'contact' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'designation' : IDL.Text,
  'createdAt' : Timestamp,
  'site' : IDL.Text,
  'joiningDate' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'employmentType' : EmploymentType,
  'empCode' : IDL.Text,
  'department' : IDL.Text,
  'empStatus' : EmployeeStatus,
});
export const Result_43 = IDL.Variant({ 'ok' : EmployeeView, 'err' : IDL.Text });
export const EnergyType = IDL.Variant({
  'Gas' : IDL.Null,
  'LPG' : IDL.Null,
  'Renewable' : IDL.Null,
  'Electricity' : IDL.Null,
  'Diesel' : IDL.Null,
});
export const AddEnergyInput = IDL.Record({
  'month' : IDL.Nat,
  'carbonEquivalent' : IDL.Float64,
  'unit' : IDL.Text,
  'year' : IDL.Nat,
  'target' : IDL.Float64,
  'energyType' : EnergyType,
  'department' : IDL.Text,
  'consumption' : IDL.Float64,
});
export const HazardType = IDL.Variant({
  'Ergonomic' : IDL.Null,
  'Chemical' : IDL.Null,
  'Biological' : IDL.Null,
  'Psychological' : IDL.Null,
  'Physical' : IDL.Null,
  'Environmental' : IDL.Null,
});
export const EmployeeId = IDL.Nat;
export const WasteType = IDL.Variant({
  'Hazardous' : IDL.Null,
  'General' : IDL.Null,
  'Recyclable' : IDL.Null,
  'Scheduled' : IDL.Null,
});
export const AddWasteInput = IDL.Record({
  'wasteType' : WasteType,
  'disposalMethod' : IDL.Text,
  'unit' : IDL.Text,
  'manifestNumber' : IDL.Text,
  'quantity' : IDL.Float64,
  'department' : IDL.Text,
  'disposalDate' : IDL.Text,
  'contractorName' : IDL.Text,
});
export const WaterSource = IDL.Variant({
  'Recycled' : IDL.Null,
  'Groundwater' : IDL.Null,
  'Municipal' : IDL.Null,
});
export const AddWaterInput = IDL.Record({
  'month' : IDL.Nat,
  'source' : WaterSource,
  'year' : IDL.Nat,
  'target' : IDL.Float64,
  'department' : IDL.Text,
  'consumption' : IDL.Float64,
});
export const Result_5 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const RiskLevel = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Critical' : IDL.Null,
});
export const RiskScoreView = IDL.Record({
  'overallScore' : IDL.Nat,
  'calculatedAt' : Timestamp,
  'calculatedBy' : IDL.Text,
  'unsafeObsCount' : IDL.Nat,
  'openHighCriticalIncidents' : IDL.Nat,
  'nearMissCount' : IDL.Nat,
  'trainingGapCount' : IDL.Nat,
  'departmentScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'riskLevel' : RiskLevel,
  'overdueCAPACount' : IDL.Nat,
});
export const Result_51 = IDL.Variant({
  'ok' : RiskScoreView,
  'err' : IDL.Text,
});
export const RootCauseCat = IDL.Variant({
  'ProcedureGap' : IDL.Null,
  'ManagementSystem' : IDL.Null,
  'HumanError' : IDL.Null,
  'TrainingGap' : IDL.Null,
  'Environmental' : IDL.Null,
  'EquipmentFailure' : IDL.Null,
});
export const CAPASource2 = IDL.Variant({
  'JSA' : IDL.Null,
  'HIRA' : IDL.Null,
  'Incident' : IDL.Null,
  'Observation' : IDL.Null,
  'Audit' : IDL.Null,
  'Manual' : IDL.Null,
});
export const CAPAType = IDL.Variant({
  'Corrective' : IDL.Null,
  'Preventive' : IDL.Null,
});
export const CAPAPriority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Critical' : IDL.Null,
});
export const CreateCAPAInput = IDL.Record({
  'rootCauseCat' : RootCauseCat,
  'source' : CAPASource2,
  'findingDescription' : IDL.Text,
  'targetDate' : IDL.Text,
  'linkedRecordNumber' : IDL.Text,
  'capaType' : CAPAType,
  'priority' : CAPAPriority,
  'actionDescription' : IDL.Text,
  'actionOwnerEmpId' : EmployeeId,
  'department' : IDL.Text,
  'rootCauseDesc' : IDL.Text,
});
export const CreateContractorInput = IDL.Record({
  'contactPerson' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'email' : IDL.Text,
  'contractEndDate' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
  'contractStartDate' : IDL.Text,
  'typeOfWork' : IDL.Text,
});
export const CreateHIRAInput = IDL.Record({
  'responsibleEmpId' : IDL.Opt(EmployeeId),
  'area' : IDL.Text,
  'taskDescription' : IDL.Text,
  'reviewDate' : IDL.Text,
  'department' : IDL.Text,
  'location' : IDL.Text,
});
export const CreateJSAInput = IDL.Record({
  'linkedPtwNumber' : IDL.Opt(IDL.Text),
  'helmetRequired' : IDL.Bool,
  'analysisDate' : IDL.Text,
  'area' : IDL.Text,
  'faceShield' : IDL.Bool,
  'emergencyContacts' : IDL.Text,
  'jobTitle' : IDL.Text,
  'harness' : IDL.Bool,
  'respirator' : IDL.Bool,
  'safetyShoes' : IDL.Bool,
  'gloves' : IDL.Bool,
  'goggles' : IDL.Bool,
  'department' : IDL.Text,
  'location' : IDL.Text,
});
export const CreateLOTOInput = IDL.Record({
  'equipmentName' : IDL.Text,
  'workDescription' : IDL.Text,
  'tagNumber' : IDL.Text,
  'startDateTime' : Timestamp,
});
export const ObservationType = IDL.Variant({
  'UnsafeAct' : IDL.Null,
  'UnsafeCondition' : IDL.Null,
  'SafeAct' : IDL.Null,
  'PositiveReinforcement' : IDL.Null,
  'NearMiss' : IDL.Null,
});
export const ObservationSeverity = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const CreateObservationInput = IDL.Record({
  'area' : IDL.Text,
  'description' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'immediateAction' : IDL.Text,
  'obsType' : ObservationType,
  'severity' : ObservationSeverity,
  'department' : IDL.Text,
  'dateTime' : Timestamp,
  'location' : IDL.Text,
});
export const PermitExtension = IDL.Record({
  'newEndTime' : Timestamp,
  'originalEndTime' : Timestamp,
  'extendedAt' : Timestamp,
  'extendedBy' : EmployeeId,
  'reason' : IDL.Text,
});
export const PTWExtension = IDL.Record({
  'isCancelled' : IDL.Bool,
  'toolboxAttendees' : IDL.Vec(EmployeeId),
  'requiresLOTO' : IDL.Bool,
  'permitNumber' : IDL.Text,
  'cancellationReason' : IDL.Opt(IDL.Text),
  'gasTestCO' : IDL.Opt(IDL.Float64),
  'gasTestO2' : IDL.Opt(IDL.Float64),
  'createdAt' : Timestamp,
  'linkedJsaNumber' : IDL.Opt(IDL.Text),
  'cancelledAt' : IDL.Opt(Timestamp),
  'cancelledBy' : IDL.Opt(EmployeeId),
  'gasTestH2S' : IDL.Opt(IDL.Float64),
  'gasTestLEL' : IDL.Opt(IDL.Float64),
  'extensions' : IDL.Vec(PermitExtension),
  'gasTestPassed' : IDL.Bool,
  'linkedHiraNumber' : IDL.Opt(IDL.Text),
  'emergencyRescueDesc' : IDL.Opt(IDL.Text),
  'emergencyRescuePlan' : IDL.Bool,
  'toolboxTalkDone' : IDL.Bool,
});
export const InsuranceType = IDL.Variant({
  'ESI' : IDL.Null,
  'GroupAccident' : IDL.Null,
  'WorkerCompensation' : IDL.Null,
  'EmployeeCompensation' : IDL.Null,
});
export const InsuranceInfo = IDL.Record({
  'insuranceType' : InsuranceType,
  'documentUrls' : IDL.Vec(IDL.Text),
  'validFrom' : IDL.Text,
  'validTill' : IDL.Text,
  'policyNumber' : IDL.Text,
  'verificationStatus' : IDL.Text,
});
export const PermitType = IDL.Variant({
  'HotWork' : IDL.Null,
  'HeightWork' : IDL.Null,
  'Shutdown' : IDL.Null,
  'ConfinedSpace' : IDL.Null,
  'Lifting' : IDL.Null,
  'ElectricalWork' : IDL.Null,
  'ChemicalHandling' : IDL.Null,
  'GeneralWork' : IDL.Null,
  'Excavation' : IDL.Null,
  'ColdWork' : IDL.Null,
});
export const IsolationDetail = IDL.Record({
  'serviceOptions' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'isolationRequired' : IDL.Bool,
  'electricalOptions' : IDL.Vec(IDL.Text),
  'isolationBy' : EmployeeId,
  'isolationDateTime' : IDL.Opt(Timestamp),
  'lotoLockNumber' : IDL.Text,
  'verificationStatus' : IDL.Text,
});
export const CreatePermitInput = IDL.Record({
  'crossReference' : IDL.Text,
  'nominatedHodEmployeeId' : IDL.Opt(EmployeeId),
  'supervisorName' : IDL.Text,
  'selectedPPE' : IDL.Vec(IDL.Text),
  'timeStart' : IDL.Text,
  'jobLocation' : IDL.Text,
  'area' : IDL.Text,
  'jobDescription' : IDL.Text,
  'validityDate' : IDL.Text,
  'insurance' : IDL.Opt(InsuranceInfo),
  'permitType' : PermitType,
  'issuingDepartment' : IDL.Text,
  'isolation' : IDL.Opt(IsolationDetail),
  'selectedHazards' : IDL.Vec(IDL.Text),
  'checklist' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'customHazard' : IDL.Text,
  'issuedTo' : IDL.Text,
  'department' : IDL.Text,
  'timeEnd' : IDL.Text,
  'riskLevel' : RiskLevel,
  'contractorName' : IDL.Text,
});
export const CreatePPEItemInput = IDL.Record({
  'size' : IDL.Text,
  'shelfLifeMonths' : IDL.Nat,
  'itemName' : IDL.Text,
  'itemType' : IDL.Text,
  'standard' : IDL.Text,
});
export const TrainingType = IDL.Variant({
  'Induction' : IDL.Null,
  'Regulatory' : IDL.Null,
  'OnTheJob' : IDL.Null,
  'Refresher' : IDL.Null,
  'External' : IDL.Null,
});
export const TrainingFrequency = IDL.Variant({
  'OneTime' : IDL.Null,
  'ThreeYearly' : IDL.Null,
  'BiAnnual' : IDL.Null,
  'Annual' : IDL.Null,
});
export const CreateTrainingInput = IDL.Record({
  'attendeeCodes' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'trainer' : IDL.Text,
  'trainingDate' : IDL.Text,
  'trainingType' : TrainingType,
  'frequency' : TrainingFrequency,
  'department' : IDL.Text,
});
export const CertificateStatus = IDL.Variant({
  'Valid' : IDL.Null,
  'ExpiringSoon' : IDL.Null,
  'Expired' : IDL.Null,
});
export const AttendanceStatus = IDL.Variant({
  'Present' : IDL.Null,
  'Absent' : IDL.Null,
});
export const TrainingAttendeeView = IDL.Record({
  'certStatus' : IDL.Opt(CertificateStatus),
  'expiryDate' : IDL.Opt(IDL.Text),
  'certificateId' : IDL.Opt(IDL.Text),
  'attendance' : AttendanceStatus,
  'empCode' : IDL.Text,
  'empName' : IDL.Text,
});
export const TrainingView = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'createdById' : EmployeeId,
  'trainingId' : IDL.Text,
  'trainer' : IDL.Text,
  'trainingDate' : IDL.Text,
  'attendees' : IDL.Vec(TrainingAttendeeView),
  'trainingType' : TrainingType,
  'frequency' : TrainingFrequency,
  'department' : IDL.Text,
});
export const Result_23 = IDL.Variant({ 'ok' : TrainingView, 'err' : IDL.Text });
export const Role = IDL.Variant({
  'HOD' : IDL.Null,
  'SystemAdmin' : IDL.Null,
  'ContractorAdmin' : IDL.Null,
  'Employee' : IDL.Null,
  'AreaInCharge' : IDL.Null,
  'SafetyOfficer' : IDL.Null,
});
export const CreateUserInput = IDL.Record({
  'password' : IDL.Text,
  'designation' : IDL.Text,
  'role' : Role,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'employeeId' : EmployeeId,
  'department' : IDL.Text,
});
export const UserStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
});
export const UserView = IDL.Record({
  'status' : UserStatus,
  'designation' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'employeeId' : EmployeeId,
  'department' : IDL.Text,
  'lastLogin' : IDL.Opt(Timestamp),
  'roles' : IDL.Vec(Role),
  'mustChangePassword' : IDL.Bool,
});
export const Result = IDL.Variant({ 'ok' : UserView, 'err' : IDL.Text });
export const Result_50 = IDL.Variant({
  'ok' : IDL.Record({
    'byDept' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'total' : IDL.Nat,
    'safe' : IDL.Nat,
    'unsafe' : IDL.Nat,
    'score' : IDL.Nat,
  }),
  'err' : IDL.Text,
});
export const CAPAStatus2 = IDL.Variant({
  'Open' : IDL.Null,
  'Closed' : IDL.Null,
  'PendingVerification' : IDL.Null,
  'Overdue' : IDL.Null,
  'InProgress' : IDL.Null,
});
export const CAPA2View = IDL.Record({
  'status' : CAPAStatus2,
  'rootCauseCat' : RootCauseCat,
  'source' : CAPASource2,
  'createdAt' : Timestamp,
  'findingDescription' : IDL.Text,
  'verifiedByEmpId' : IDL.Opt(EmployeeId),
  'updatedAt' : Timestamp,
  'progressUpdate' : IDL.Text,
  'completionEvidence' : IDL.Opt(IDL.Text),
  'targetDate' : IDL.Text,
  'linkedRecordNumber' : IDL.Text,
  'isOverdue' : IDL.Bool,
  'capaType' : CAPAType,
  'priority' : CAPAPriority,
  'actionDescription' : IDL.Text,
  'actionOwnerEmpId' : EmployeeId,
  'department' : IDL.Text,
  'rootCauseDesc' : IDL.Text,
  'verifiedAt' : IDL.Opt(Timestamp),
  'capaNumber' : IDL.Text,
});
export const Result_49 = IDL.Variant({ 'ok' : CAPA2View, 'err' : IDL.Text });
export const Result_48 = IDL.Variant({
  'ok' : IDL.Record({
    'byDept' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'closed' : IDL.Nat,
    'closureRate' : IDL.Nat,
    'total' : IDL.Nat,
    'open' : IDL.Nat,
    'overdue' : IDL.Nat,
    'avgDaysToClose' : IDL.Float64,
    'inProgress' : IDL.Nat,
    'bySource' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  }),
  'err' : IDL.Text,
});
export const ContractorStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Blacklisted' : IDL.Null,
  'Expired' : IDL.Null,
});
export const ContractorDocStatus = IDL.Variant({
  'Expiring' : IDL.Null,
  'Valid' : IDL.Null,
  'Expired' : IDL.Null,
});
export const ContractorDocView = IDL.Record({
  'status' : ContractorDocStatus,
  'expiryDate' : IDL.Text,
  'docType' : IDL.Text,
  'uploadedAt' : Timestamp,
});
export const ContractorEmployeeView = IDL.Record({
  'trade' : IDL.Text,
  'inductionStatus' : InductionStatus,
  'inductionDate' : IDL.Opt(IDL.Text),
  'idNumber' : IDL.Text,
  'empName' : IDL.Text,
  'certificateNumber' : IDL.Opt(IDL.Text),
});
export const PerformanceRating = IDL.Variant({
  'Fair' : IDL.Null,
  'Good' : IDL.Null,
  'Poor' : IDL.Null,
  'Excellent' : IDL.Null,
});
export const ContractorPerformance = IDL.Record({
  'evaluatedAt' : Timestamp,
  'evaluatedBy' : EmployeeId,
  'ptwCompliance' : IDL.Float64,
  'overallRating' : PerformanceRating,
  'safetyScore' : IDL.Nat,
  'incidentCount' : IDL.Nat,
  'nearMissCount' : IDL.Nat,
  'trainingCompliance' : IDL.Float64,
});
export const ContractorView = IDL.Record({
  'status' : ContractorStatus,
  'documents' : IDL.Vec(ContractorDocView),
  'employees' : IDL.Vec(ContractorEmployeeView),
  'createdAt' : Timestamp,
  'contactPerson' : IDL.Text,
  'contractorId' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'email' : IDL.Text,
  'contractEndDate' : IDL.Text,
  'updatedAt' : Timestamp,
  'performance' : IDL.Opt(ContractorPerformance),
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
  'contractStartDate' : IDL.Text,
  'typeOfWork' : IDL.Text,
  'linkedPtwNumbers' : IDL.Vec(IDL.Text),
});
export const Result_47 = IDL.Variant({
  'ok' : ContractorView,
  'err' : IDL.Text,
});
export const Result_46 = IDL.Variant({
  'ok' : IDL.Record({
    'performanceSummary' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'incidentCount' : IDL.Nat,
    'activeCount' : IDL.Nat,
    'inductionCompliance' : IDL.Nat,
    'expiringDocs' : IDL.Nat,
  }),
  'err' : IDL.Text,
});
export const Result_36 = IDL.Variant({
  'ok' : IDL.Vec(IDL.Text),
  'err' : IDL.Text,
});
export const DeptOHSEScore = IDL.Record({
  'score' : IDL.Float64,
  'department' : IDL.Text,
});
export const Result_45 = IDL.Variant({
  'ok' : IDL.Vec(DeptOHSEScore),
  'err' : IDL.Text,
});
export const Result_44 = IDL.Variant({
  'ok' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Text)),
  'err' : IDL.Text,
});
export const AirEmissionEntry = IDL.Record({
  'value' : IDL.Float64,
  'source' : AirEmissionSource,
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'pollutant' : AirPollutant,
  'isExceeded' : IDL.Bool,
  'measurementDate' : IDL.Text,
  'department' : IDL.Text,
  'regulatoryLimit' : IDL.Float64,
  'loggedBy' : EmployeeId,
});
export const EffluentEntry = IDL.Record({
  'samplingDate' : IDL.Text,
  'isCompliant' : IDL.Bool,
  'value' : IDL.Float64,
  'parameter' : EffluentParameter,
  'createdAt' : Timestamp,
  'effluentType' : EffluentType,
  'department' : IDL.Text,
  'regulatoryLimit' : IDL.Float64,
  'loggedBy' : EmployeeId,
});
export const CarbonEntry = IDL.Record({
  'month' : IDL.Nat,
  'co2eTonnes' : IDL.Float64,
  'createdAt' : Timestamp,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'scope' : CarbonScope,
  'loggedBy' : EmployeeId,
});
export const WasteEntry = IDL.Record({
  'wasteType' : WasteType,
  'disposalMethod' : IDL.Text,
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'manifestNumber' : IDL.Text,
  'quantity' : IDL.Float64,
  'department' : IDL.Text,
  'disposalDate' : IDL.Text,
  'loggedBy' : EmployeeId,
  'contractorName' : IDL.Text,
});
export const WaterEntry = IDL.Record({
  'month' : IDL.Nat,
  'source' : WaterSource,
  'createdAt' : Timestamp,
  'year' : IDL.Nat,
  'target' : IDL.Float64,
  'department' : IDL.Text,
  'loggedBy' : EmployeeId,
  'consumption' : IDL.Float64,
});
export const EnergyEntry = IDL.Record({
  'month' : IDL.Nat,
  'carbonEquivalent' : IDL.Float64,
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'year' : IDL.Nat,
  'target' : IDL.Float64,
  'energyType' : EnergyType,
  'department' : IDL.Text,
  'loggedBy' : EmployeeId,
  'consumption' : IDL.Float64,
});
export const Result_42 = IDL.Variant({
  'ok' : IDL.Record({
    'air' : IDL.Vec(AirEmissionEntry),
    'effluent' : IDL.Vec(EffluentEntry),
    'esgScore' : IDL.Nat,
    'carbon' : IDL.Vec(CarbonEntry),
    'waste' : IDL.Vec(WasteEntry),
    'water' : IDL.Vec(WaterEntry),
    'energy' : IDL.Vec(EnergyEntry),
  }),
  'err' : IDL.Text,
});
export const Result_41 = IDL.Variant({
  'ok' : IDL.Record({
    'complianceRate' : IDL.Nat,
    'carbonTotal' : IDL.Float64,
    'trendData' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'esgScore' : IDL.Nat,
    'waterTotal' : IDL.Float64,
    'wasteTotal' : IDL.Float64,
    'energyTotal' : IDL.Float64,
  }),
  'err' : IDL.Text,
});
export const HIRAStatus = IDL.Variant({
  'UnderReview' : IDL.Null,
  'Approved' : IDL.Null,
  'Draft' : IDL.Null,
  'Expired' : IDL.Null,
});
export const HazardRow = IDL.Record({
  'responsibleEmpId' : IDL.Opt(EmployeeId),
  'hazardType' : HazardType,
  'hazardDescription' : IDL.Text,
  'residualRiskScore' : IDL.Nat,
  'additionalControls' : IDL.Text,
  'severity' : IDL.Nat,
  'existingControls' : IDL.Text,
  'likelihood' : IDL.Nat,
  'riskLevel' : RiskLevel,
  'riskScore' : IDL.Nat,
  'hazardId' : IDL.Text,
});
export const HIRAView = IDL.Record({
  'status' : HIRAStatus,
  'responsibleEmpId' : IDL.Opt(EmployeeId),
  'soEmpId' : IDL.Opt(EmployeeId),
  'linkedPtwNumber' : IDL.Opt(IDL.Text),
  'aicAt' : IDL.Opt(Timestamp),
  'hodAt' : IDL.Opt(Timestamp),
  'hazards' : IDL.Vec(HazardRow),
  'aicRemarks' : IDL.Opt(IDL.Text),
  'area' : IDL.Text,
  'hodEmpId' : IDL.Opt(EmployeeId),
  'soRemarks' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'createdBy' : EmployeeId,
  'soAt' : IDL.Opt(Timestamp),
  'aicEmpId' : IDL.Opt(EmployeeId),
  'taskDescription' : IDL.Text,
  'reviewDate' : IDL.Text,
  'approvalStep' : IDL.Nat,
  'updatedAt' : Timestamp,
  'hodRemarks' : IDL.Opt(IDL.Text),
  'hiraNumber' : IDL.Text,
  'department' : IDL.Text,
  'location' : IDL.Text,
});
export const Result_40 = IDL.Variant({ 'ok' : HIRAView, 'err' : IDL.Text });
export const IncidentStatus = IDL.Variant({
  'UnderInvestigation' : IDL.Null,
  'Open' : IDL.Null,
  'Closed' : IDL.Null,
  'CAPAPending' : IDL.Null,
});
export const Severity = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Critical' : IDL.Null,
});
export const IncidentType = IDL.Variant({
  'LTI' : IDL.Null,
  'UnsafeAct' : IDL.Null,
  'UnsafeCondition' : IDL.Null,
  'NearMiss' : IDL.Null,
  'Fatal' : IDL.Null,
  'FirstAid' : IDL.Null,
});
export const IncidentView = IDL.Record({
  'status' : IncidentStatus,
  'reportedByName' : IDL.Text,
  'reportedById' : EmployeeId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'closedAt' : IDL.Opt(Timestamp),
  'injuredPersonCode' : IDL.Opt(IDL.Text),
  'incidentNumber' : IDL.Text,
  'severity' : Severity,
  'department' : IDL.Text,
  'correctiveAction' : IDL.Text,
  'location' : IDL.Text,
  'incidentDate' : IDL.Text,
  'incidentType' : IncidentType,
  'rootCause' : IDL.Text,
});
export const Result_4 = IDL.Variant({ 'ok' : IncidentView, 'err' : IDL.Text });
export const MonthlyTrend = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'incidentCount' : IDL.Nat,
});
export const Result_39 = IDL.Variant({
  'ok' : IDL.Vec(MonthlyTrend),
  'err' : IDL.Text,
});
export const JSAStatus = IDL.Variant({
  'UnderReview' : IDL.Null,
  'Closed' : IDL.Null,
  'Active' : IDL.Null,
  'Approved' : IDL.Null,
  'Draft' : IDL.Null,
});
export const JSAStep = IDL.Record({
  'stepNo' : IDL.Nat,
  'responsibleEmpId' : IDL.Opt(EmployeeId),
  'hazards' : IDL.Text,
  'controls' : IDL.Text,
  'description' : IDL.Text,
  'riskLevel' : RiskLevel,
});
export const JSAView = IDL.Record({
  'status' : JSAStatus,
  'linkedPtwNumber' : IDL.Opt(IDL.Text),
  'hodAt' : IDL.Opt(Timestamp),
  'helmetRequired' : IDL.Bool,
  'analysisDate' : IDL.Text,
  'area' : IDL.Text,
  'soRemarks' : IDL.Opt(IDL.Text),
  'approvedBy' : IDL.Opt(EmployeeId),
  'createdAt' : Timestamp,
  'soAt' : IDL.Opt(Timestamp),
  'faceShield' : IDL.Bool,
  'emergencyContacts' : IDL.Text,
  'reviewedBy' : IDL.Opt(EmployeeId),
  'preparedBy' : EmployeeId,
  'updatedAt' : Timestamp,
  'steps' : IDL.Vec(JSAStep),
  'jobTitle' : IDL.Text,
  'briefingAttendees' : IDL.Vec(EmployeeId),
  'harness' : IDL.Bool,
  'respirator' : IDL.Bool,
  'jsaNumber' : IDL.Text,
  'hodRemarks' : IDL.Opt(IDL.Text),
  'safetyShoes' : IDL.Bool,
  'gloves' : IDL.Bool,
  'goggles' : IDL.Bool,
  'department' : IDL.Text,
  'location' : IDL.Text,
});
export const Result_38 = IDL.Variant({ 'ok' : JSAView, 'err' : IDL.Text });
export const KPISummary = IDL.Record({
  'trainingCompliancePct' : IDL.Float64,
  'auditScorePct' : IDL.Float64,
  'trir' : IDL.Float64,
  'ptwCompliancePct' : IDL.Float64,
  'ltifr' : IDL.Float64,
  'openCAPAs' : IDL.Nat,
  'nearMissCount' : IDL.Nat,
  'totalIncidents' : IDL.Nat,
});
export const Result_37 = IDL.Variant({ 'ok' : KPISummary, 'err' : IDL.Text });
export const LOTOStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Draft' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
});
export const EnergySourceLOTO = IDL.Variant({
  'Chemical' : IDL.Null,
  'Hydraulic' : IDL.Null,
  'Gravitational' : IDL.Null,
  'Mechanical' : IDL.Null,
  'Thermal' : IDL.Null,
  'Pneumatic' : IDL.Null,
  'Electrical' : IDL.Null,
});
export const LockEntryStatus = IDL.Variant({
  'Applied' : IDL.Null,
  'Removed' : IDL.Null,
});
export const LockEntryView = IDL.Record({
  'status' : LockEntryStatus,
  'assignedEmpId' : EmployeeId,
  'lockNumber' : IDL.Text,
});
export const IsolationPointStatus = IDL.Variant({
  'Applied' : IDL.Null,
  'Removed' : IDL.Null,
});
export const IsolationPoint = IDL.Record({
  'status' : IsolationPointStatus,
  'pointId' : IDL.Text,
  'location' : IDL.Text,
  'lockNumber' : IDL.Text,
});
export const LOTOView = IDL.Record({
  'status' : LOTOStatus,
  'reEnergizationChecklist' : IDL.Vec(IDL.Text),
  'createdAt' : Timestamp,
  'createdBy' : EmployeeId,
  'equipmentName' : IDL.Text,
  'lotoNumber' : IDL.Text,
  'authorizedAt' : IDL.Opt(Timestamp),
  'workDescription' : IDL.Text,
  'updatedAt' : Timestamp,
  'endDateTime' : IDL.Opt(Timestamp),
  'energySources' : IDL.Vec(EnergySourceLOTO),
  'lockRegister' : IDL.Vec(LockEntryView),
  'tagNumber' : IDL.Text,
  'authorizedEmpIds' : IDL.Vec(EmployeeId),
  'isolationPoints' : IDL.Vec(IsolationPoint),
  'startDateTime' : Timestamp,
  'authorizedByEmpId' : IDL.Opt(EmployeeId),
  'procedureSteps' : IDL.Vec(IDL.Text),
});
export const Result_35 = IDL.Variant({ 'ok' : LOTOView, 'err' : IDL.Text });
export const Result_34 = IDL.Variant({
  'ok' : IDL.Record({
    'active' : IDL.Nat,
    'completedThisMonth' : IDL.Nat,
    'overdue' : IDL.Nat,
  }),
  'err' : IDL.Text,
});
export const NotificationView = IDL.Record({
  'id' : IDL.Nat,
  'link' : IDL.Text,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'recipientId' : EmployeeId,
});
export const Result_33 = IDL.Variant({
  'ok' : IDL.Vec(NotificationView),
  'err' : IDL.Text,
});
export const ObservationStatus = IDL.Variant({
  'UnderReview' : IDL.Null,
  'Open' : IDL.Null,
  'Closed' : IDL.Null,
  'CAPAPending' : IDL.Null,
});
export const ObservationView = IDL.Record({
  'status' : ObservationStatus,
  'acknowledgedAt' : IDL.Opt(Timestamp),
  'acknowledgedBy' : IDL.Opt(EmployeeId),
  'linkedCapaId' : IDL.Opt(IDL.Text),
  'area' : IDL.Text,
  'createdAt' : Timestamp,
  'observerName' : IDL.Text,
  'description' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'immediateAction' : IDL.Text,
  'observerEmpId' : EmployeeId,
  'acknowledgeRemarks' : IDL.Opt(IDL.Text),
  'obsType' : ObservationType,
  'severity' : ObservationSeverity,
  'department' : IDL.Text,
  'dateTime' : Timestamp,
  'obsNumber' : IDL.Text,
  'location' : IDL.Text,
});
export const Result_32 = IDL.Variant({
  'ok' : ObservationView,
  'err' : IDL.Text,
});
export const ApprovalSignature = IDL.Record({
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'approvalStatus' : IDL.Text,
  'signedAt' : IDL.Opt(Timestamp),
  'employeeId' : EmployeeId,
  'remarks' : IDL.Text,
  'ipAddress' : IDL.Text,
});
export const PTWStatus = IDL.Variant({
  'Closed' : IDL.Null,
  'HODReview' : IDL.Null,
  'Active' : IDL.Null,
  'IsolationReview' : IDL.Null,
  'AreaReview' : IDL.Null,
  'Approved' : IDL.Null,
  'Suspended' : IDL.Null,
  'Draft' : IDL.Null,
  'Rejected' : IDL.Null,
  'FinalApproval' : IDL.Null,
  'Submitted' : IDL.Null,
  'SafetyReview' : IDL.Null,
  'Expired' : IDL.Null,
});
export const EnergisationRecord = IDL.Record({
  'signature' : IDL.Text,
  'approverEmployeeId' : EmployeeId,
  'approvedAt' : IDL.Opt(Timestamp),
  'approverName' : IDL.Text,
  'checklistItems' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'lotoLockNumber' : IDL.Text,
  'energisationType' : IDL.Text,
});
export const PermitToWorkView = IDL.Record({
  'id' : IDL.Text,
  'requestorSignature' : IDL.Opt(ApprovalSignature),
  'status' : PTWStatus,
  'crossReference' : IDL.Text,
  'safetyOfficerSignature' : IDL.Opt(ApprovalSignature),
  'nominatedHodEmployeeId' : IDL.Opt(EmployeeId),
  'nominatedAreaInChargeEmployeeId' : IDL.Opt(EmployeeId),
  'supervisorName' : IDL.Text,
  'selectedPPE' : IDL.Vec(IDL.Text),
  'isolationAuthoritySignature' : IDL.Opt(ApprovalSignature),
  'timeStart' : IDL.Text,
  'jobLocation' : IDL.Text,
  'area' : IDL.Text,
  'jobDescription' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : EmployeeId,
  'coPpm' : IDL.Opt(IDL.Float64),
  'linkedJsaNumber' : IDL.Opt(IDL.Text),
  'validityDate' : IDL.Text,
  'hodSignature' : IDL.Opt(ApprovalSignature),
  'insurance' : IDL.Opt(InsuranceInfo),
  'nominatedIsolationAuthorityEmployeeId' : IDL.Opt(EmployeeId),
  'nominatedFinalIssuerEmployeeId' : IDL.Opt(EmployeeId),
  'electricalEnergisation' : IDL.Opt(EnergisationRecord),
  'updatedAt' : Timestamp,
  'permitType' : PermitType,
  'areaInChargeSignature' : IDL.Opt(ApprovalSignature),
  'issuingDepartment' : IDL.Text,
  'isolation' : IDL.Opt(IsolationDetail),
  'selectedHazards' : IDL.Vec(IDL.Text),
  'electricalApproverSignature' : IDL.Opt(ApprovalSignature),
  'serviceProcessEnergisation' : IDL.Opt(EnergisationRecord),
  'h2sPpm' : IDL.Opt(IDL.Float64),
  'checklist' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'serviceProcessApproverSignature' : IDL.Opt(ApprovalSignature),
  'emergencyRescueDescription' : IDL.Text,
  'toolboxTalkAttendees' : IDL.Vec(IDL.Text),
  'customHazard' : IDL.Text,
  'issuedTo' : IDL.Text,
  'lelPercent' : IDL.Opt(IDL.Float64),
  'department' : IDL.Text,
  'timeEnd' : IDL.Text,
  'nominatedSafetyOfficerEmployeeId' : IDL.Opt(EmployeeId),
  'riskLevel' : RiskLevel,
  'linkedHiraNumber' : IDL.Opt(IDL.Text),
  'o2Percent' : IDL.Opt(IDL.Float64),
  'contractorName' : IDL.Text,
  'finalIssuerSignature' : IDL.Opt(ApprovalSignature),
  'emergencyRescuePlan' : IDL.Bool,
  'toolboxTalkDone' : IDL.Bool,
});
export const Result_31 = IDL.Variant({
  'ok' : PermitToWorkView,
  'err' : IDL.Text,
});
export const PTWMasterData = IDL.Record({
  'departments' : IDL.Vec(IDL.Text),
  'hazards' : IDL.Vec(IDL.Text),
  'ppeList' : IDL.Vec(IDL.Text),
  'permitTypes' : IDL.Vec(IDL.Text),
  'locations' : IDL.Vec(IDL.Text),
});
export const Result_30 = IDL.Variant({
  'ok' : PTWMasterData,
  'err' : IDL.Text,
});
export const Result_29 = IDL.Variant({
  'ok' : IDL.Record({
    'complianceRate' : IDL.Nat,
    'issuanceCount' : IDL.Nat,
    'lowStockItems' : IDL.Nat,
    'totalItems' : IDL.Nat,
  }),
  'err' : IDL.Text,
});
export const Result_28 = IDL.Variant({
  'ok' : IDL.Record({
    'byType' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'avgCycleTimeDays' : IDL.Float64,
    'cancelledThisMonth' : IDL.Nat,
  }),
  'err' : IDL.Text,
});
export const PTWExtensionView = IDL.Record({
  'isCancelled' : IDL.Bool,
  'toolboxAttendees' : IDL.Vec(EmployeeId),
  'requiresLOTO' : IDL.Bool,
  'permitNumber' : IDL.Text,
  'cancellationReason' : IDL.Opt(IDL.Text),
  'gasTestCO' : IDL.Opt(IDL.Float64),
  'gasTestO2' : IDL.Opt(IDL.Float64),
  'createdAt' : Timestamp,
  'linkedJsaNumber' : IDL.Opt(IDL.Text),
  'cancelledAt' : IDL.Opt(Timestamp),
  'cancelledBy' : IDL.Opt(EmployeeId),
  'gasTestH2S' : IDL.Opt(IDL.Float64),
  'gasTestLEL' : IDL.Opt(IDL.Float64),
  'extensions' : IDL.Vec(PermitExtension),
  'gasTestPassed' : IDL.Bool,
  'linkedHiraNumber' : IDL.Opt(IDL.Text),
  'emergencyRescueDesc' : IDL.Opt(IDL.Text),
  'emergencyRescuePlan' : IDL.Bool,
  'toolboxTalkDone' : IDL.Bool,
});
export const Result_27 = IDL.Variant({
  'ok' : IDL.Opt(PTWExtensionView),
  'err' : IDL.Text,
});
export const Result_26 = IDL.Variant({
  'ok' : IDL.Vec(
    IDL.Record({
      'severity' : IDL.Text,
      'recommendation' : IDL.Text,
      'driver' : IDL.Text,
    })
  ),
  'err' : IDL.Text,
});
export const Result_25 = IDL.Variant({
  'ok' : IDL.Vec(RiskScoreView),
  'err' : IDL.Text,
});
export const Result_24 = IDL.Variant({
  'ok' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'err' : IDL.Text,
});
export const PPEConditionIssue = IDL.Variant({
  'New' : IDL.Null,
  'Reissued' : IDL.Null,
});
export const AuditAction = IDL.Variant({
  'Login' : IDL.Null,
  'Deactivated' : IDL.Null,
  'Reactivated' : IDL.Null,
  'Closed' : IDL.Null,
  'PasswordChanged' : IDL.Null,
  'Updated' : IDL.Null,
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Logout' : IDL.Null,
  'PasswordReset' : IDL.Null,
  'Created' : IDL.Null,
});
export const AuditEntry = IDL.Record({
  'id' : IDL.Nat,
  'action' : AuditAction,
  'actorName' : IDL.Text,
  'actorRole' : Role,
  'actorId' : EmployeeId,
  'detail' : IDL.Text,
  'timestamp' : Timestamp,
  'module' : IDL.Text,
  'recordRef' : IDL.Text,
});
export const Result_22 = IDL.Variant({
  'ok' : IDL.Vec(AuditEntry),
  'err' : IDL.Text,
});
export const CAPAStatus = IDL.Variant({
  'Open' : IDL.Null,
  'Closed' : IDL.Null,
  'Overdue' : IDL.Null,
  'InProgress' : IDL.Null,
});
export const CAPAView = IDL.Record({
  'id' : IDL.Nat,
  'status' : CAPAStatus,
  'actionOwnerId' : EmployeeId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'closedAt' : IDL.Opt(Timestamp),
  'actionOwnerName' : IDL.Text,
  'incidentNumber' : IDL.Text,
});
export const Result_21 = IDL.Variant({
  'ok' : IDL.Vec(CAPAView),
  'err' : IDL.Text,
});
export const Result_20 = IDL.Variant({
  'ok' : IDL.Vec(CAPA2View),
  'err' : IDL.Text,
});
export const Result_19 = IDL.Variant({
  'ok' : IDL.Vec(ContractorView),
  'err' : IDL.Text,
});
export const Result_18 = IDL.Variant({
  'ok' : IDL.Vec(EmployeeView),
  'err' : IDL.Text,
});
export const Result_17 = IDL.Variant({
  'ok' : IDL.Vec(HIRAView),
  'err' : IDL.Text,
});
export const Result_16 = IDL.Variant({
  'ok' : IDL.Vec(IncidentView),
  'err' : IDL.Text,
});
export const Result_15 = IDL.Variant({
  'ok' : IDL.Vec(JSAView),
  'err' : IDL.Text,
});
export const Result_14 = IDL.Variant({
  'ok' : IDL.Vec(LOTOView),
  'err' : IDL.Text,
});
export const Result_13 = IDL.Variant({
  'ok' : IDL.Vec(ObservationView),
  'err' : IDL.Text,
});
export const Result_12 = IDL.Variant({
  'ok' : IDL.Vec(PermitToWorkView),
  'err' : IDL.Text,
});
export const PPEInventoryView = IDL.Record({
  'itemId' : IDL.Text,
  'quantityInStock' : IDL.Int,
  'lastUpdated' : Timestamp,
  'minStockLevel' : IDL.Nat,
});
export const Result_11 = IDL.Variant({
  'ok' : IDL.Vec(PPEInventoryView),
  'err' : IDL.Text,
});
export const PPEIssuance = IDL.Record({
  'issueDate' : IDL.Text,
  'itemId' : IDL.Text,
  'createdAt' : Timestamp,
  'size' : IDL.Text,
  'employeeId' : EmployeeId,
  'quantity' : IDL.Nat,
  'issuanceId' : IDL.Text,
  'condition' : PPEConditionIssue,
});
export const Result_10 = IDL.Variant({
  'ok' : IDL.Vec(PPEIssuance),
  'err' : IDL.Text,
});
export const PPEItem = IDL.Record({
  'itemId' : IDL.Text,
  'createdAt' : Timestamp,
  'size' : IDL.Text,
  'shelfLifeMonths' : IDL.Nat,
  'itemName' : IDL.Text,
  'itemType' : IDL.Text,
  'standard' : IDL.Text,
});
export const Result_9 = IDL.Variant({
  'ok' : IDL.Vec(PPEItem),
  'err' : IDL.Text,
});
export const Result_8 = IDL.Variant({
  'ok' : IDL.Vec(TrainingView),
  'err' : IDL.Text,
});
export const Result_7 = IDL.Variant({
  'ok' : IDL.Vec(UserView),
  'err' : IDL.Text,
});
export const Result_6 = IDL.Variant({
  'ok' : IDL.Record({ 'token' : IDL.Text, 'mustChangePassword' : IDL.Bool }),
  'err' : IDL.Text,
});
export const PPEInspectionCondition = IDL.Variant({
  'Good' : IDL.Null,
  'Replace' : IDL.Null,
  'Damaged' : IDL.Null,
});
export const CreateIncidentInput = IDL.Record({
  'description' : IDL.Text,
  'capaActionOwnerId' : EmployeeId,
  'capaDeadline' : IDL.Text,
  'injuredPersonCode' : IDL.Opt(IDL.Text),
  'severity' : Severity,
  'department' : IDL.Text,
  'location' : IDL.Text,
  'incidentDate' : IDL.Text,
  'incidentType' : IncidentType,
});
export const Result_3 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const Result_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'acknowledgeObservation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'actOnHIRA' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [Result_1],
      [],
    ),
  'actOnJSA' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [Result_1],
      [],
    ),
  'activateLoto' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'addAirEmission' : IDL.Func([IDL.Text, AddAirEmissionInput], [Result_1], []),
  'addCarbonEntry' : IDL.Func([IDL.Text, AddCarbonInput], [Result_1], []),
  'addContractorDocument' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'addContractorEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, ContractorEmployee],
      [Result_1],
      [],
    ),
  'addEffluentEntry' : IDL.Func([IDL.Text, AddEffluentInput], [Result_1], []),
  'addEmployee' : IDL.Func([IDL.Text, AddEmployeeInput], [Result_43], []),
  'addEnergyEntry' : IDL.Func([IDL.Text, AddEnergyInput], [Result_1], []),
  'addHazardRow' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        HazardType,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(EmployeeId),
      ],
      [Result_1],
      [],
    ),
  'addWasteEntry' : IDL.Func([IDL.Text, AddWasteInput], [Result_1], []),
  'addWaterEntry' : IDL.Func([IDL.Text, AddWaterInput], [Result_1], []),
  'answerRiskQuery' : IDL.Func([IDL.Text, IDL.Text], [Result_5], ['query']),
  'approvePTWAreaInCharge' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Result_1],
      [],
    ),
  'approvePTWFinalIssuer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'approvePTWHOD' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Result_1],
      [],
    ),
  'approvePTWIsolationAuthority' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Result_1],
      [],
    ),
  'approvePTWSafetyOfficer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Result_1],
      [],
    ),
  'calculateRiskScore' : IDL.Func([IDL.Text], [Result_51], []),
  'cancelLoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_1], []),
  'cancelPermit' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_1], []),
  'changePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_1], []),
  'checkAndUpdateDocumentStatuses' : IDL.Func([], [], []),
  'checkOverdueCapas' : IDL.Func([], [], []),
  'closeCAPA' : IDL.Func([IDL.Text, IDL.Nat], [Result_1], []),
  'closeObservation' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'closePTW' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'completeLoto' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'createCapa2' : IDL.Func([IDL.Text, CreateCAPAInput], [Result_5], []),
  'createContractor' : IDL.Func(
      [IDL.Text, CreateContractorInput],
      [Result_5],
      [],
    ),
  'createHIRA' : IDL.Func([IDL.Text, CreateHIRAInput], [Result_5], []),
  'createJSA' : IDL.Func([IDL.Text, CreateJSAInput], [Result_5], []),
  'createLoto' : IDL.Func([IDL.Text, CreateLOTOInput], [Result_5], []),
  'createObservation' : IDL.Func(
      [IDL.Text, CreateObservationInput],
      [Result_5],
      [],
    ),
  'createOrUpdatePtwExtension' : IDL.Func(
      [IDL.Text, IDL.Text, PTWExtension],
      [Result_1],
      [],
    ),
  'createPTW' : IDL.Func([IDL.Text, CreatePermitInput], [Result_5], []),
  'createPpeItem' : IDL.Func([IDL.Text, CreatePPEItemInput], [Result_5], []),
  'createTraining' : IDL.Func([IDL.Text, CreateTrainingInput], [Result_23], []),
  'createUser' : IDL.Func([IDL.Text, CreateUserInput], [Result], []),
  'extendPermit' : IDL.Func(
      [IDL.Text, IDL.Text, Timestamp, IDL.Text],
      [Result_1],
      [],
    ),
  'getBbsStats' : IDL.Func([IDL.Text], [Result_50], ['query']),
  'getCapa2' : IDL.Func([IDL.Text, IDL.Text], [Result_49], ['query']),
  'getCapa2Stats' : IDL.Func([IDL.Text], [Result_48], ['query']),
  'getContractor' : IDL.Func([IDL.Text, IDL.Text], [Result_47], ['query']),
  'getContractorStats' : IDL.Func([IDL.Text], [Result_46], ['query']),
  'getDepartments' : IDL.Func([IDL.Text], [Result_36], ['query']),
  'getDeptOHSEScores' : IDL.Func([IDL.Text], [Result_45], ['query']),
  'getDeptRiskBreakdown' : IDL.Func([IDL.Text], [Result_44], ['query']),
  'getEmployee' : IDL.Func([IDL.Text, IDL.Text], [Result_43], ['query']),
  'getEsgData' : IDL.Func([IDL.Text], [Result_42], ['query']),
  'getEsgStats' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
      [Result_41],
      ['query'],
    ),
  'getHIRA' : IDL.Func([IDL.Text, IDL.Text], [Result_40], ['query']),
  'getIncident' : IDL.Func([IDL.Text, IDL.Text], [Result_4], ['query']),
  'getIncidentTrend' : IDL.Func([IDL.Text, IDL.Nat], [Result_39], ['query']),
  'getJSA' : IDL.Func([IDL.Text, IDL.Text], [Result_38], ['query']),
  'getKPISummary' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [Result_37],
      ['query'],
    ),
  'getLocations' : IDL.Func([IDL.Text], [Result_36], ['query']),
  'getLoto' : IDL.Func([IDL.Text, IDL.Text], [Result_35], ['query']),
  'getLotoStats' : IDL.Func([IDL.Text], [Result_34], ['query']),
  'getNotifications' : IDL.Func([IDL.Text], [Result_33], ['query']),
  'getObservation' : IDL.Func([IDL.Text, IDL.Text], [Result_32], ['query']),
  'getPTW' : IDL.Func([IDL.Text, IDL.Text], [Result_31], ['query']),
  'getPTWMasterData' : IDL.Func([IDL.Text], [Result_30], ['query']),
  'getPpeStats' : IDL.Func([IDL.Text], [Result_29], ['query']),
  'getPtwDashboardStats' : IDL.Func([IDL.Text], [Result_28], ['query']),
  'getPtwExtension' : IDL.Func([IDL.Text, IDL.Text], [Result_27], ['query']),
  'getRiskRecommendations' : IDL.Func([IDL.Text], [Result_26], ['query']),
  'getRiskScoreHistory' : IDL.Func([IDL.Text], [Result_25], ['query']),
  'getRiskScoreTrend' : IDL.Func([IDL.Text], [Result_24], ['query']),
  'getTraining' : IDL.Func([IDL.Text, IDL.Text], [Result_23], ['query']),
  'issuePpe' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, PPEConditionIssue],
      [Result_5],
      [],
    ),
  'linkContractorToPtw' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'listAuditEntries' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(Timestamp), IDL.Opt(Timestamp)],
      [Result_22],
      ['query'],
    ),
  'listCAPAs' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Result_21], ['query']),
  'listCapa2s' : IDL.Func([IDL.Text], [Result_20], ['query']),
  'listContractors' : IDL.Func([IDL.Text], [Result_19], ['query']),
  'listEmployees' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(EmployeeStatus),
        IDL.Opt(IDL.Text),
      ],
      [Result_18],
      ['query'],
    ),
  'listHIRAs' : IDL.Func([IDL.Text], [Result_17], ['query']),
  'listIncidents' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IncidentType),
        IDL.Opt(Severity),
        IDL.Opt(IncidentStatus),
        IDL.Opt(IDL.Text),
      ],
      [Result_16],
      ['query'],
    ),
  'listJSAs' : IDL.Func([IDL.Text], [Result_15], ['query']),
  'listLotos' : IDL.Func([IDL.Text], [Result_14], ['query']),
  'listObservations' : IDL.Func([IDL.Text], [Result_13], ['query']),
  'listPTWs' : IDL.Func(
      [IDL.Text, IDL.Opt(PTWStatus), IDL.Opt(PermitType)],
      [Result_12],
      ['query'],
    ),
  'listPpeInventory' : IDL.Func([IDL.Text], [Result_11], ['query']),
  'listPpeIssuances' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat)],
      [Result_10],
      ['query'],
    ),
  'listPpeItems' : IDL.Func([IDL.Text], [Result_9], ['query']),
  'listTrainings' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(TrainingType)],
      [Result_8],
      ['query'],
    ),
  'listUsers' : IDL.Func(
      [IDL.Text, IDL.Opt(Role), IDL.Opt(IDL.Text), IDL.Opt(UserStatus)],
      [Result_7],
      ['query'],
    ),
  'login' : IDL.Func([EmployeeId, IDL.Text], [Result_6], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'markAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, AttendanceStatus],
      [Result_1],
      [],
    ),
  'markNotifRead' : IDL.Func([IDL.Text, IDL.Nat], [Result_1], []),
  'recordContractorPerformance' : IDL.Func(
      [IDL.Text, IDL.Text, ContractorPerformance],
      [Result_1],
      [],
    ),
  'recordEnergisation' : IDL.Func(
      [IDL.Text, IDL.Text, EnergisationRecord],
      [Result_1],
      [],
    ),
  'recordInduction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [Result_5],
      [],
    ),
  'recordJSABriefing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(EmployeeId)],
      [Result_1],
      [],
    ),
  'recordPpeInspection' : IDL.Func(
      [IDL.Text, IDL.Text, PPEInspectionCondition, IDL.Text, IDL.Text],
      [Result_5],
      [],
    ),
  'recordToolboxTalk' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(EmployeeId)],
      [Result_1],
      [],
    ),
  'rejectPTW' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_1], []),
  'reportIncident' : IDL.Func([IDL.Text, CreateIncidentInput], [Result_4], []),
  'resetPassword' : IDL.Func([IDL.Text, EmployeeId, IDL.Text], [Result_1], []),
  'setPtwGasTest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [Result_3],
      [],
    ),
  'setUserStatus' : IDL.Func(
      [IDL.Text, EmployeeId, UserStatus],
      [Result_1],
      [],
    ),
  'submitCapa2ForVerification' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'submitHIRAForApproval' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'submitJSAForApproval' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'submitPTW' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Result_1], []),
  'suspendPTW' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_1], []),
  'unreadNotifCount' : IDL.Func([IDL.Text], [Result_2], ['query']),
  'updateCapa2Progress' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Result_1],
      [],
    ),
  'updateContractorStatus' : IDL.Func(
      [IDL.Text, IDL.Text, ContractorStatus],
      [Result_1],
      [],
    ),
  'updateIncidentStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IncidentStatus, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'updateLockStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, LockEntryStatus],
      [Result_1],
      [],
    ),
  'updatePpeInventory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Nat],
      [Result_1],
      [],
    ),
  'verifyCapa2' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [Result_1],
      [],
    ),
  'whoAmI' : IDL.Func([IDL.Text], [Result], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const AirEmissionSource = IDL.Variant({
    'Stack' : IDL.Null,
    'Vehicle' : IDL.Null,
    'Fugitive' : IDL.Null,
  });
  const AirPollutant = IDL.Variant({
    'CO2' : IDL.Null,
    'NOx' : IDL.Null,
    'SOx' : IDL.Null,
    'VOC' : IDL.Null,
    'PM10' : IDL.Null,
  });
  const AddAirEmissionInput = IDL.Record({
    'value' : IDL.Float64,
    'source' : AirEmissionSource,
    'unit' : IDL.Text,
    'pollutant' : AirPollutant,
    'measurementDate' : IDL.Text,
    'department' : IDL.Text,
    'regulatoryLimit' : IDL.Float64,
  });
  const CarbonScope = IDL.Variant({
    'Scope1' : IDL.Null,
    'Scope2' : IDL.Null,
    'Scope3' : IDL.Null,
  });
  const AddCarbonInput = IDL.Record({
    'month' : IDL.Nat,
    'co2eTonnes' : IDL.Float64,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'scope' : CarbonScope,
  });
  const InductionStatus = IDL.Variant({
    'Fail' : IDL.Null,
    'Pass' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ContractorEmployee = IDL.Record({
    'trade' : IDL.Text,
    'inductionStatus' : InductionStatus,
    'inductionDate' : IDL.Opt(IDL.Text),
    'idNumber' : IDL.Text,
    'empName' : IDL.Text,
    'certificateNumber' : IDL.Opt(IDL.Text),
  });
  const EffluentParameter = IDL.Variant({
    'PH' : IDL.Null,
    'BOD' : IDL.Null,
    'COD' : IDL.Null,
    'TSS' : IDL.Null,
    'HeavyMetals' : IDL.Null,
  });
  const EffluentType = IDL.Variant({
    'Domestic' : IDL.Null,
    'Stormwater' : IDL.Null,
    'Process' : IDL.Null,
  });
  const AddEffluentInput = IDL.Record({
    'samplingDate' : IDL.Text,
    'value' : IDL.Float64,
    'parameter' : EffluentParameter,
    'effluentType' : EffluentType,
    'department' : IDL.Text,
    'regulatoryLimit' : IDL.Float64,
  });
  const EmploymentType = IDL.Variant({
    'Contract' : IDL.Null,
    'FullTime' : IDL.Null,
    'Temporary' : IDL.Null,
  });
  const AddEmployeeInput = IDL.Record({
    'contact' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'designation' : IDL.Text,
    'site' : IDL.Text,
    'joiningDate' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'employmentType' : EmploymentType,
    'department' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const EmployeeStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
    'Resigned' : IDL.Null,
  });
  const EmployeeView = IDL.Record({
    'contact' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'designation' : IDL.Text,
    'createdAt' : Timestamp,
    'site' : IDL.Text,
    'joiningDate' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'employmentType' : EmploymentType,
    'empCode' : IDL.Text,
    'department' : IDL.Text,
    'empStatus' : EmployeeStatus,
  });
  const Result_43 = IDL.Variant({ 'ok' : EmployeeView, 'err' : IDL.Text });
  const EnergyType = IDL.Variant({
    'Gas' : IDL.Null,
    'LPG' : IDL.Null,
    'Renewable' : IDL.Null,
    'Electricity' : IDL.Null,
    'Diesel' : IDL.Null,
  });
  const AddEnergyInput = IDL.Record({
    'month' : IDL.Nat,
    'carbonEquivalent' : IDL.Float64,
    'unit' : IDL.Text,
    'year' : IDL.Nat,
    'target' : IDL.Float64,
    'energyType' : EnergyType,
    'department' : IDL.Text,
    'consumption' : IDL.Float64,
  });
  const HazardType = IDL.Variant({
    'Ergonomic' : IDL.Null,
    'Chemical' : IDL.Null,
    'Biological' : IDL.Null,
    'Psychological' : IDL.Null,
    'Physical' : IDL.Null,
    'Environmental' : IDL.Null,
  });
  const EmployeeId = IDL.Nat;
  const WasteType = IDL.Variant({
    'Hazardous' : IDL.Null,
    'General' : IDL.Null,
    'Recyclable' : IDL.Null,
    'Scheduled' : IDL.Null,
  });
  const AddWasteInput = IDL.Record({
    'wasteType' : WasteType,
    'disposalMethod' : IDL.Text,
    'unit' : IDL.Text,
    'manifestNumber' : IDL.Text,
    'quantity' : IDL.Float64,
    'department' : IDL.Text,
    'disposalDate' : IDL.Text,
    'contractorName' : IDL.Text,
  });
  const WaterSource = IDL.Variant({
    'Recycled' : IDL.Null,
    'Groundwater' : IDL.Null,
    'Municipal' : IDL.Null,
  });
  const AddWaterInput = IDL.Record({
    'month' : IDL.Nat,
    'source' : WaterSource,
    'year' : IDL.Nat,
    'target' : IDL.Float64,
    'department' : IDL.Text,
    'consumption' : IDL.Float64,
  });
  const Result_5 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const RiskLevel = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const RiskScoreView = IDL.Record({
    'overallScore' : IDL.Nat,
    'calculatedAt' : Timestamp,
    'calculatedBy' : IDL.Text,
    'unsafeObsCount' : IDL.Nat,
    'openHighCriticalIncidents' : IDL.Nat,
    'nearMissCount' : IDL.Nat,
    'trainingGapCount' : IDL.Nat,
    'departmentScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'riskLevel' : RiskLevel,
    'overdueCAPACount' : IDL.Nat,
  });
  const Result_51 = IDL.Variant({ 'ok' : RiskScoreView, 'err' : IDL.Text });
  const RootCauseCat = IDL.Variant({
    'ProcedureGap' : IDL.Null,
    'ManagementSystem' : IDL.Null,
    'HumanError' : IDL.Null,
    'TrainingGap' : IDL.Null,
    'Environmental' : IDL.Null,
    'EquipmentFailure' : IDL.Null,
  });
  const CAPASource2 = IDL.Variant({
    'JSA' : IDL.Null,
    'HIRA' : IDL.Null,
    'Incident' : IDL.Null,
    'Observation' : IDL.Null,
    'Audit' : IDL.Null,
    'Manual' : IDL.Null,
  });
  const CAPAType = IDL.Variant({
    'Corrective' : IDL.Null,
    'Preventive' : IDL.Null,
  });
  const CAPAPriority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const CreateCAPAInput = IDL.Record({
    'rootCauseCat' : RootCauseCat,
    'source' : CAPASource2,
    'findingDescription' : IDL.Text,
    'targetDate' : IDL.Text,
    'linkedRecordNumber' : IDL.Text,
    'capaType' : CAPAType,
    'priority' : CAPAPriority,
    'actionDescription' : IDL.Text,
    'actionOwnerEmpId' : EmployeeId,
    'department' : IDL.Text,
    'rootCauseDesc' : IDL.Text,
  });
  const CreateContractorInput = IDL.Record({
    'contactPerson' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'email' : IDL.Text,
    'contractEndDate' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
    'contractStartDate' : IDL.Text,
    'typeOfWork' : IDL.Text,
  });
  const CreateHIRAInput = IDL.Record({
    'responsibleEmpId' : IDL.Opt(EmployeeId),
    'area' : IDL.Text,
    'taskDescription' : IDL.Text,
    'reviewDate' : IDL.Text,
    'department' : IDL.Text,
    'location' : IDL.Text,
  });
  const CreateJSAInput = IDL.Record({
    'linkedPtwNumber' : IDL.Opt(IDL.Text),
    'helmetRequired' : IDL.Bool,
    'analysisDate' : IDL.Text,
    'area' : IDL.Text,
    'faceShield' : IDL.Bool,
    'emergencyContacts' : IDL.Text,
    'jobTitle' : IDL.Text,
    'harness' : IDL.Bool,
    'respirator' : IDL.Bool,
    'safetyShoes' : IDL.Bool,
    'gloves' : IDL.Bool,
    'goggles' : IDL.Bool,
    'department' : IDL.Text,
    'location' : IDL.Text,
  });
  const CreateLOTOInput = IDL.Record({
    'equipmentName' : IDL.Text,
    'workDescription' : IDL.Text,
    'tagNumber' : IDL.Text,
    'startDateTime' : Timestamp,
  });
  const ObservationType = IDL.Variant({
    'UnsafeAct' : IDL.Null,
    'UnsafeCondition' : IDL.Null,
    'SafeAct' : IDL.Null,
    'PositiveReinforcement' : IDL.Null,
    'NearMiss' : IDL.Null,
  });
  const ObservationSeverity = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const CreateObservationInput = IDL.Record({
    'area' : IDL.Text,
    'description' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'immediateAction' : IDL.Text,
    'obsType' : ObservationType,
    'severity' : ObservationSeverity,
    'department' : IDL.Text,
    'dateTime' : Timestamp,
    'location' : IDL.Text,
  });
  const PermitExtension = IDL.Record({
    'newEndTime' : Timestamp,
    'originalEndTime' : Timestamp,
    'extendedAt' : Timestamp,
    'extendedBy' : EmployeeId,
    'reason' : IDL.Text,
  });
  const PTWExtension = IDL.Record({
    'isCancelled' : IDL.Bool,
    'toolboxAttendees' : IDL.Vec(EmployeeId),
    'requiresLOTO' : IDL.Bool,
    'permitNumber' : IDL.Text,
    'cancellationReason' : IDL.Opt(IDL.Text),
    'gasTestCO' : IDL.Opt(IDL.Float64),
    'gasTestO2' : IDL.Opt(IDL.Float64),
    'createdAt' : Timestamp,
    'linkedJsaNumber' : IDL.Opt(IDL.Text),
    'cancelledAt' : IDL.Opt(Timestamp),
    'cancelledBy' : IDL.Opt(EmployeeId),
    'gasTestH2S' : IDL.Opt(IDL.Float64),
    'gasTestLEL' : IDL.Opt(IDL.Float64),
    'extensions' : IDL.Vec(PermitExtension),
    'gasTestPassed' : IDL.Bool,
    'linkedHiraNumber' : IDL.Opt(IDL.Text),
    'emergencyRescueDesc' : IDL.Opt(IDL.Text),
    'emergencyRescuePlan' : IDL.Bool,
    'toolboxTalkDone' : IDL.Bool,
  });
  const InsuranceType = IDL.Variant({
    'ESI' : IDL.Null,
    'GroupAccident' : IDL.Null,
    'WorkerCompensation' : IDL.Null,
    'EmployeeCompensation' : IDL.Null,
  });
  const InsuranceInfo = IDL.Record({
    'insuranceType' : InsuranceType,
    'documentUrls' : IDL.Vec(IDL.Text),
    'validFrom' : IDL.Text,
    'validTill' : IDL.Text,
    'policyNumber' : IDL.Text,
    'verificationStatus' : IDL.Text,
  });
  const PermitType = IDL.Variant({
    'HotWork' : IDL.Null,
    'HeightWork' : IDL.Null,
    'Shutdown' : IDL.Null,
    'ConfinedSpace' : IDL.Null,
    'Lifting' : IDL.Null,
    'ElectricalWork' : IDL.Null,
    'ChemicalHandling' : IDL.Null,
    'GeneralWork' : IDL.Null,
    'Excavation' : IDL.Null,
    'ColdWork' : IDL.Null,
  });
  const IsolationDetail = IDL.Record({
    'serviceOptions' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'isolationRequired' : IDL.Bool,
    'electricalOptions' : IDL.Vec(IDL.Text),
    'isolationBy' : EmployeeId,
    'isolationDateTime' : IDL.Opt(Timestamp),
    'lotoLockNumber' : IDL.Text,
    'verificationStatus' : IDL.Text,
  });
  const CreatePermitInput = IDL.Record({
    'crossReference' : IDL.Text,
    'nominatedHodEmployeeId' : IDL.Opt(EmployeeId),
    'supervisorName' : IDL.Text,
    'selectedPPE' : IDL.Vec(IDL.Text),
    'timeStart' : IDL.Text,
    'jobLocation' : IDL.Text,
    'area' : IDL.Text,
    'jobDescription' : IDL.Text,
    'validityDate' : IDL.Text,
    'insurance' : IDL.Opt(InsuranceInfo),
    'permitType' : PermitType,
    'issuingDepartment' : IDL.Text,
    'isolation' : IDL.Opt(IsolationDetail),
    'selectedHazards' : IDL.Vec(IDL.Text),
    'checklist' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'customHazard' : IDL.Text,
    'issuedTo' : IDL.Text,
    'department' : IDL.Text,
    'timeEnd' : IDL.Text,
    'riskLevel' : RiskLevel,
    'contractorName' : IDL.Text,
  });
  const CreatePPEItemInput = IDL.Record({
    'size' : IDL.Text,
    'shelfLifeMonths' : IDL.Nat,
    'itemName' : IDL.Text,
    'itemType' : IDL.Text,
    'standard' : IDL.Text,
  });
  const TrainingType = IDL.Variant({
    'Induction' : IDL.Null,
    'Regulatory' : IDL.Null,
    'OnTheJob' : IDL.Null,
    'Refresher' : IDL.Null,
    'External' : IDL.Null,
  });
  const TrainingFrequency = IDL.Variant({
    'OneTime' : IDL.Null,
    'ThreeYearly' : IDL.Null,
    'BiAnnual' : IDL.Null,
    'Annual' : IDL.Null,
  });
  const CreateTrainingInput = IDL.Record({
    'attendeeCodes' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'trainer' : IDL.Text,
    'trainingDate' : IDL.Text,
    'trainingType' : TrainingType,
    'frequency' : TrainingFrequency,
    'department' : IDL.Text,
  });
  const CertificateStatus = IDL.Variant({
    'Valid' : IDL.Null,
    'ExpiringSoon' : IDL.Null,
    'Expired' : IDL.Null,
  });
  const AttendanceStatus = IDL.Variant({
    'Present' : IDL.Null,
    'Absent' : IDL.Null,
  });
  const TrainingAttendeeView = IDL.Record({
    'certStatus' : IDL.Opt(CertificateStatus),
    'expiryDate' : IDL.Opt(IDL.Text),
    'certificateId' : IDL.Opt(IDL.Text),
    'attendance' : AttendanceStatus,
    'empCode' : IDL.Text,
    'empName' : IDL.Text,
  });
  const TrainingView = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'createdById' : EmployeeId,
    'trainingId' : IDL.Text,
    'trainer' : IDL.Text,
    'trainingDate' : IDL.Text,
    'attendees' : IDL.Vec(TrainingAttendeeView),
    'trainingType' : TrainingType,
    'frequency' : TrainingFrequency,
    'department' : IDL.Text,
  });
  const Result_23 = IDL.Variant({ 'ok' : TrainingView, 'err' : IDL.Text });
  const Role = IDL.Variant({
    'HOD' : IDL.Null,
    'SystemAdmin' : IDL.Null,
    'ContractorAdmin' : IDL.Null,
    'Employee' : IDL.Null,
    'AreaInCharge' : IDL.Null,
    'SafetyOfficer' : IDL.Null,
  });
  const CreateUserInput = IDL.Record({
    'password' : IDL.Text,
    'designation' : IDL.Text,
    'role' : Role,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'employeeId' : EmployeeId,
    'department' : IDL.Text,
  });
  const UserStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
  });
  const UserView = IDL.Record({
    'status' : UserStatus,
    'designation' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'employeeId' : EmployeeId,
    'department' : IDL.Text,
    'lastLogin' : IDL.Opt(Timestamp),
    'roles' : IDL.Vec(Role),
    'mustChangePassword' : IDL.Bool,
  });
  const Result = IDL.Variant({ 'ok' : UserView, 'err' : IDL.Text });
  const Result_50 = IDL.Variant({
    'ok' : IDL.Record({
      'byDept' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
      'total' : IDL.Nat,
      'safe' : IDL.Nat,
      'unsafe' : IDL.Nat,
      'score' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const CAPAStatus2 = IDL.Variant({
    'Open' : IDL.Null,
    'Closed' : IDL.Null,
    'PendingVerification' : IDL.Null,
    'Overdue' : IDL.Null,
    'InProgress' : IDL.Null,
  });
  const CAPA2View = IDL.Record({
    'status' : CAPAStatus2,
    'rootCauseCat' : RootCauseCat,
    'source' : CAPASource2,
    'createdAt' : Timestamp,
    'findingDescription' : IDL.Text,
    'verifiedByEmpId' : IDL.Opt(EmployeeId),
    'updatedAt' : Timestamp,
    'progressUpdate' : IDL.Text,
    'completionEvidence' : IDL.Opt(IDL.Text),
    'targetDate' : IDL.Text,
    'linkedRecordNumber' : IDL.Text,
    'isOverdue' : IDL.Bool,
    'capaType' : CAPAType,
    'priority' : CAPAPriority,
    'actionDescription' : IDL.Text,
    'actionOwnerEmpId' : EmployeeId,
    'department' : IDL.Text,
    'rootCauseDesc' : IDL.Text,
    'verifiedAt' : IDL.Opt(Timestamp),
    'capaNumber' : IDL.Text,
  });
  const Result_49 = IDL.Variant({ 'ok' : CAPA2View, 'err' : IDL.Text });
  const Result_48 = IDL.Variant({
    'ok' : IDL.Record({
      'byDept' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
      'closed' : IDL.Nat,
      'closureRate' : IDL.Nat,
      'total' : IDL.Nat,
      'open' : IDL.Nat,
      'overdue' : IDL.Nat,
      'avgDaysToClose' : IDL.Float64,
      'inProgress' : IDL.Nat,
      'bySource' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    }),
    'err' : IDL.Text,
  });
  const ContractorStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Blacklisted' : IDL.Null,
    'Expired' : IDL.Null,
  });
  const ContractorDocStatus = IDL.Variant({
    'Expiring' : IDL.Null,
    'Valid' : IDL.Null,
    'Expired' : IDL.Null,
  });
  const ContractorDocView = IDL.Record({
    'status' : ContractorDocStatus,
    'expiryDate' : IDL.Text,
    'docType' : IDL.Text,
    'uploadedAt' : Timestamp,
  });
  const ContractorEmployeeView = IDL.Record({
    'trade' : IDL.Text,
    'inductionStatus' : InductionStatus,
    'inductionDate' : IDL.Opt(IDL.Text),
    'idNumber' : IDL.Text,
    'empName' : IDL.Text,
    'certificateNumber' : IDL.Opt(IDL.Text),
  });
  const PerformanceRating = IDL.Variant({
    'Fair' : IDL.Null,
    'Good' : IDL.Null,
    'Poor' : IDL.Null,
    'Excellent' : IDL.Null,
  });
  const ContractorPerformance = IDL.Record({
    'evaluatedAt' : Timestamp,
    'evaluatedBy' : EmployeeId,
    'ptwCompliance' : IDL.Float64,
    'overallRating' : PerformanceRating,
    'safetyScore' : IDL.Nat,
    'incidentCount' : IDL.Nat,
    'nearMissCount' : IDL.Nat,
    'trainingCompliance' : IDL.Float64,
  });
  const ContractorView = IDL.Record({
    'status' : ContractorStatus,
    'documents' : IDL.Vec(ContractorDocView),
    'employees' : IDL.Vec(ContractorEmployeeView),
    'createdAt' : Timestamp,
    'contactPerson' : IDL.Text,
    'contractorId' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'email' : IDL.Text,
    'contractEndDate' : IDL.Text,
    'updatedAt' : Timestamp,
    'performance' : IDL.Opt(ContractorPerformance),
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
    'contractStartDate' : IDL.Text,
    'typeOfWork' : IDL.Text,
    'linkedPtwNumbers' : IDL.Vec(IDL.Text),
  });
  const Result_47 = IDL.Variant({ 'ok' : ContractorView, 'err' : IDL.Text });
  const Result_46 = IDL.Variant({
    'ok' : IDL.Record({
      'performanceSummary' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
      'incidentCount' : IDL.Nat,
      'activeCount' : IDL.Nat,
      'inductionCompliance' : IDL.Nat,
      'expiringDocs' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const Result_36 = IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text });
  const DeptOHSEScore = IDL.Record({
    'score' : IDL.Float64,
    'department' : IDL.Text,
  });
  const Result_45 = IDL.Variant({
    'ok' : IDL.Vec(DeptOHSEScore),
    'err' : IDL.Text,
  });
  const Result_44 = IDL.Variant({
    'ok' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Text)),
    'err' : IDL.Text,
  });
  const AirEmissionEntry = IDL.Record({
    'value' : IDL.Float64,
    'source' : AirEmissionSource,
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'pollutant' : AirPollutant,
    'isExceeded' : IDL.Bool,
    'measurementDate' : IDL.Text,
    'department' : IDL.Text,
    'regulatoryLimit' : IDL.Float64,
    'loggedBy' : EmployeeId,
  });
  const EffluentEntry = IDL.Record({
    'samplingDate' : IDL.Text,
    'isCompliant' : IDL.Bool,
    'value' : IDL.Float64,
    'parameter' : EffluentParameter,
    'createdAt' : Timestamp,
    'effluentType' : EffluentType,
    'department' : IDL.Text,
    'regulatoryLimit' : IDL.Float64,
    'loggedBy' : EmployeeId,
  });
  const CarbonEntry = IDL.Record({
    'month' : IDL.Nat,
    'co2eTonnes' : IDL.Float64,
    'createdAt' : Timestamp,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'scope' : CarbonScope,
    'loggedBy' : EmployeeId,
  });
  const WasteEntry = IDL.Record({
    'wasteType' : WasteType,
    'disposalMethod' : IDL.Text,
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'manifestNumber' : IDL.Text,
    'quantity' : IDL.Float64,
    'department' : IDL.Text,
    'disposalDate' : IDL.Text,
    'loggedBy' : EmployeeId,
    'contractorName' : IDL.Text,
  });
  const WaterEntry = IDL.Record({
    'month' : IDL.Nat,
    'source' : WaterSource,
    'createdAt' : Timestamp,
    'year' : IDL.Nat,
    'target' : IDL.Float64,
    'department' : IDL.Text,
    'loggedBy' : EmployeeId,
    'consumption' : IDL.Float64,
  });
  const EnergyEntry = IDL.Record({
    'month' : IDL.Nat,
    'carbonEquivalent' : IDL.Float64,
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'year' : IDL.Nat,
    'target' : IDL.Float64,
    'energyType' : EnergyType,
    'department' : IDL.Text,
    'loggedBy' : EmployeeId,
    'consumption' : IDL.Float64,
  });
  const Result_42 = IDL.Variant({
    'ok' : IDL.Record({
      'air' : IDL.Vec(AirEmissionEntry),
      'effluent' : IDL.Vec(EffluentEntry),
      'esgScore' : IDL.Nat,
      'carbon' : IDL.Vec(CarbonEntry),
      'waste' : IDL.Vec(WasteEntry),
      'water' : IDL.Vec(WaterEntry),
      'energy' : IDL.Vec(EnergyEntry),
    }),
    'err' : IDL.Text,
  });
  const Result_41 = IDL.Variant({
    'ok' : IDL.Record({
      'complianceRate' : IDL.Nat,
      'carbonTotal' : IDL.Float64,
      'trendData' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
      'esgScore' : IDL.Nat,
      'waterTotal' : IDL.Float64,
      'wasteTotal' : IDL.Float64,
      'energyTotal' : IDL.Float64,
    }),
    'err' : IDL.Text,
  });
  const HIRAStatus = IDL.Variant({
    'UnderReview' : IDL.Null,
    'Approved' : IDL.Null,
    'Draft' : IDL.Null,
    'Expired' : IDL.Null,
  });
  const HazardRow = IDL.Record({
    'responsibleEmpId' : IDL.Opt(EmployeeId),
    'hazardType' : HazardType,
    'hazardDescription' : IDL.Text,
    'residualRiskScore' : IDL.Nat,
    'additionalControls' : IDL.Text,
    'severity' : IDL.Nat,
    'existingControls' : IDL.Text,
    'likelihood' : IDL.Nat,
    'riskLevel' : RiskLevel,
    'riskScore' : IDL.Nat,
    'hazardId' : IDL.Text,
  });
  const HIRAView = IDL.Record({
    'status' : HIRAStatus,
    'responsibleEmpId' : IDL.Opt(EmployeeId),
    'soEmpId' : IDL.Opt(EmployeeId),
    'linkedPtwNumber' : IDL.Opt(IDL.Text),
    'aicAt' : IDL.Opt(Timestamp),
    'hodAt' : IDL.Opt(Timestamp),
    'hazards' : IDL.Vec(HazardRow),
    'aicRemarks' : IDL.Opt(IDL.Text),
    'area' : IDL.Text,
    'hodEmpId' : IDL.Opt(EmployeeId),
    'soRemarks' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'createdBy' : EmployeeId,
    'soAt' : IDL.Opt(Timestamp),
    'aicEmpId' : IDL.Opt(EmployeeId),
    'taskDescription' : IDL.Text,
    'reviewDate' : IDL.Text,
    'approvalStep' : IDL.Nat,
    'updatedAt' : Timestamp,
    'hodRemarks' : IDL.Opt(IDL.Text),
    'hiraNumber' : IDL.Text,
    'department' : IDL.Text,
    'location' : IDL.Text,
  });
  const Result_40 = IDL.Variant({ 'ok' : HIRAView, 'err' : IDL.Text });
  const IncidentStatus = IDL.Variant({
    'UnderInvestigation' : IDL.Null,
    'Open' : IDL.Null,
    'Closed' : IDL.Null,
    'CAPAPending' : IDL.Null,
  });
  const Severity = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const IncidentType = IDL.Variant({
    'LTI' : IDL.Null,
    'UnsafeAct' : IDL.Null,
    'UnsafeCondition' : IDL.Null,
    'NearMiss' : IDL.Null,
    'Fatal' : IDL.Null,
    'FirstAid' : IDL.Null,
  });
  const IncidentView = IDL.Record({
    'status' : IncidentStatus,
    'reportedByName' : IDL.Text,
    'reportedById' : EmployeeId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'closedAt' : IDL.Opt(Timestamp),
    'injuredPersonCode' : IDL.Opt(IDL.Text),
    'incidentNumber' : IDL.Text,
    'severity' : Severity,
    'department' : IDL.Text,
    'correctiveAction' : IDL.Text,
    'location' : IDL.Text,
    'incidentDate' : IDL.Text,
    'incidentType' : IncidentType,
    'rootCause' : IDL.Text,
  });
  const Result_4 = IDL.Variant({ 'ok' : IncidentView, 'err' : IDL.Text });
  const MonthlyTrend = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'incidentCount' : IDL.Nat,
  });
  const Result_39 = IDL.Variant({
    'ok' : IDL.Vec(MonthlyTrend),
    'err' : IDL.Text,
  });
  const JSAStatus = IDL.Variant({
    'UnderReview' : IDL.Null,
    'Closed' : IDL.Null,
    'Active' : IDL.Null,
    'Approved' : IDL.Null,
    'Draft' : IDL.Null,
  });
  const JSAStep = IDL.Record({
    'stepNo' : IDL.Nat,
    'responsibleEmpId' : IDL.Opt(EmployeeId),
    'hazards' : IDL.Text,
    'controls' : IDL.Text,
    'description' : IDL.Text,
    'riskLevel' : RiskLevel,
  });
  const JSAView = IDL.Record({
    'status' : JSAStatus,
    'linkedPtwNumber' : IDL.Opt(IDL.Text),
    'hodAt' : IDL.Opt(Timestamp),
    'helmetRequired' : IDL.Bool,
    'analysisDate' : IDL.Text,
    'area' : IDL.Text,
    'soRemarks' : IDL.Opt(IDL.Text),
    'approvedBy' : IDL.Opt(EmployeeId),
    'createdAt' : Timestamp,
    'soAt' : IDL.Opt(Timestamp),
    'faceShield' : IDL.Bool,
    'emergencyContacts' : IDL.Text,
    'reviewedBy' : IDL.Opt(EmployeeId),
    'preparedBy' : EmployeeId,
    'updatedAt' : Timestamp,
    'steps' : IDL.Vec(JSAStep),
    'jobTitle' : IDL.Text,
    'briefingAttendees' : IDL.Vec(EmployeeId),
    'harness' : IDL.Bool,
    'respirator' : IDL.Bool,
    'jsaNumber' : IDL.Text,
    'hodRemarks' : IDL.Opt(IDL.Text),
    'safetyShoes' : IDL.Bool,
    'gloves' : IDL.Bool,
    'goggles' : IDL.Bool,
    'department' : IDL.Text,
    'location' : IDL.Text,
  });
  const Result_38 = IDL.Variant({ 'ok' : JSAView, 'err' : IDL.Text });
  const KPISummary = IDL.Record({
    'trainingCompliancePct' : IDL.Float64,
    'auditScorePct' : IDL.Float64,
    'trir' : IDL.Float64,
    'ptwCompliancePct' : IDL.Float64,
    'ltifr' : IDL.Float64,
    'openCAPAs' : IDL.Nat,
    'nearMissCount' : IDL.Nat,
    'totalIncidents' : IDL.Nat,
  });
  const Result_37 = IDL.Variant({ 'ok' : KPISummary, 'err' : IDL.Text });
  const LOTOStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Draft' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const EnergySourceLOTO = IDL.Variant({
    'Chemical' : IDL.Null,
    'Hydraulic' : IDL.Null,
    'Gravitational' : IDL.Null,
    'Mechanical' : IDL.Null,
    'Thermal' : IDL.Null,
    'Pneumatic' : IDL.Null,
    'Electrical' : IDL.Null,
  });
  const LockEntryStatus = IDL.Variant({
    'Applied' : IDL.Null,
    'Removed' : IDL.Null,
  });
  const LockEntryView = IDL.Record({
    'status' : LockEntryStatus,
    'assignedEmpId' : EmployeeId,
    'lockNumber' : IDL.Text,
  });
  const IsolationPointStatus = IDL.Variant({
    'Applied' : IDL.Null,
    'Removed' : IDL.Null,
  });
  const IsolationPoint = IDL.Record({
    'status' : IsolationPointStatus,
    'pointId' : IDL.Text,
    'location' : IDL.Text,
    'lockNumber' : IDL.Text,
  });
  const LOTOView = IDL.Record({
    'status' : LOTOStatus,
    'reEnergizationChecklist' : IDL.Vec(IDL.Text),
    'createdAt' : Timestamp,
    'createdBy' : EmployeeId,
    'equipmentName' : IDL.Text,
    'lotoNumber' : IDL.Text,
    'authorizedAt' : IDL.Opt(Timestamp),
    'workDescription' : IDL.Text,
    'updatedAt' : Timestamp,
    'endDateTime' : IDL.Opt(Timestamp),
    'energySources' : IDL.Vec(EnergySourceLOTO),
    'lockRegister' : IDL.Vec(LockEntryView),
    'tagNumber' : IDL.Text,
    'authorizedEmpIds' : IDL.Vec(EmployeeId),
    'isolationPoints' : IDL.Vec(IsolationPoint),
    'startDateTime' : Timestamp,
    'authorizedByEmpId' : IDL.Opt(EmployeeId),
    'procedureSteps' : IDL.Vec(IDL.Text),
  });
  const Result_35 = IDL.Variant({ 'ok' : LOTOView, 'err' : IDL.Text });
  const Result_34 = IDL.Variant({
    'ok' : IDL.Record({
      'active' : IDL.Nat,
      'completedThisMonth' : IDL.Nat,
      'overdue' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const NotificationView = IDL.Record({
    'id' : IDL.Nat,
    'link' : IDL.Text,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'recipientId' : EmployeeId,
  });
  const Result_33 = IDL.Variant({
    'ok' : IDL.Vec(NotificationView),
    'err' : IDL.Text,
  });
  const ObservationStatus = IDL.Variant({
    'UnderReview' : IDL.Null,
    'Open' : IDL.Null,
    'Closed' : IDL.Null,
    'CAPAPending' : IDL.Null,
  });
  const ObservationView = IDL.Record({
    'status' : ObservationStatus,
    'acknowledgedAt' : IDL.Opt(Timestamp),
    'acknowledgedBy' : IDL.Opt(EmployeeId),
    'linkedCapaId' : IDL.Opt(IDL.Text),
    'area' : IDL.Text,
    'createdAt' : Timestamp,
    'observerName' : IDL.Text,
    'description' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'immediateAction' : IDL.Text,
    'observerEmpId' : EmployeeId,
    'acknowledgeRemarks' : IDL.Opt(IDL.Text),
    'obsType' : ObservationType,
    'severity' : ObservationSeverity,
    'department' : IDL.Text,
    'dateTime' : Timestamp,
    'obsNumber' : IDL.Text,
    'location' : IDL.Text,
  });
  const Result_32 = IDL.Variant({ 'ok' : ObservationView, 'err' : IDL.Text });
  const ApprovalSignature = IDL.Record({
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'approvalStatus' : IDL.Text,
    'signedAt' : IDL.Opt(Timestamp),
    'employeeId' : EmployeeId,
    'remarks' : IDL.Text,
    'ipAddress' : IDL.Text,
  });
  const PTWStatus = IDL.Variant({
    'Closed' : IDL.Null,
    'HODReview' : IDL.Null,
    'Active' : IDL.Null,
    'IsolationReview' : IDL.Null,
    'AreaReview' : IDL.Null,
    'Approved' : IDL.Null,
    'Suspended' : IDL.Null,
    'Draft' : IDL.Null,
    'Rejected' : IDL.Null,
    'FinalApproval' : IDL.Null,
    'Submitted' : IDL.Null,
    'SafetyReview' : IDL.Null,
    'Expired' : IDL.Null,
  });
  const EnergisationRecord = IDL.Record({
    'signature' : IDL.Text,
    'approverEmployeeId' : EmployeeId,
    'approvedAt' : IDL.Opt(Timestamp),
    'approverName' : IDL.Text,
    'checklistItems' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'lotoLockNumber' : IDL.Text,
    'energisationType' : IDL.Text,
  });
  const PermitToWorkView = IDL.Record({
    'id' : IDL.Text,
    'requestorSignature' : IDL.Opt(ApprovalSignature),
    'status' : PTWStatus,
    'crossReference' : IDL.Text,
    'safetyOfficerSignature' : IDL.Opt(ApprovalSignature),
    'nominatedHodEmployeeId' : IDL.Opt(EmployeeId),
    'nominatedAreaInChargeEmployeeId' : IDL.Opt(EmployeeId),
    'supervisorName' : IDL.Text,
    'selectedPPE' : IDL.Vec(IDL.Text),
    'isolationAuthoritySignature' : IDL.Opt(ApprovalSignature),
    'timeStart' : IDL.Text,
    'jobLocation' : IDL.Text,
    'area' : IDL.Text,
    'jobDescription' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : EmployeeId,
    'coPpm' : IDL.Opt(IDL.Float64),
    'linkedJsaNumber' : IDL.Opt(IDL.Text),
    'validityDate' : IDL.Text,
    'hodSignature' : IDL.Opt(ApprovalSignature),
    'insurance' : IDL.Opt(InsuranceInfo),
    'nominatedIsolationAuthorityEmployeeId' : IDL.Opt(EmployeeId),
    'nominatedFinalIssuerEmployeeId' : IDL.Opt(EmployeeId),
    'electricalEnergisation' : IDL.Opt(EnergisationRecord),
    'updatedAt' : Timestamp,
    'permitType' : PermitType,
    'areaInChargeSignature' : IDL.Opt(ApprovalSignature),
    'issuingDepartment' : IDL.Text,
    'isolation' : IDL.Opt(IsolationDetail),
    'selectedHazards' : IDL.Vec(IDL.Text),
    'electricalApproverSignature' : IDL.Opt(ApprovalSignature),
    'serviceProcessEnergisation' : IDL.Opt(EnergisationRecord),
    'h2sPpm' : IDL.Opt(IDL.Float64),
    'checklist' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'serviceProcessApproverSignature' : IDL.Opt(ApprovalSignature),
    'emergencyRescueDescription' : IDL.Text,
    'toolboxTalkAttendees' : IDL.Vec(IDL.Text),
    'customHazard' : IDL.Text,
    'issuedTo' : IDL.Text,
    'lelPercent' : IDL.Opt(IDL.Float64),
    'department' : IDL.Text,
    'timeEnd' : IDL.Text,
    'nominatedSafetyOfficerEmployeeId' : IDL.Opt(EmployeeId),
    'riskLevel' : RiskLevel,
    'linkedHiraNumber' : IDL.Opt(IDL.Text),
    'o2Percent' : IDL.Opt(IDL.Float64),
    'contractorName' : IDL.Text,
    'finalIssuerSignature' : IDL.Opt(ApprovalSignature),
    'emergencyRescuePlan' : IDL.Bool,
    'toolboxTalkDone' : IDL.Bool,
  });
  const Result_31 = IDL.Variant({ 'ok' : PermitToWorkView, 'err' : IDL.Text });
  const PTWMasterData = IDL.Record({
    'departments' : IDL.Vec(IDL.Text),
    'hazards' : IDL.Vec(IDL.Text),
    'ppeList' : IDL.Vec(IDL.Text),
    'permitTypes' : IDL.Vec(IDL.Text),
    'locations' : IDL.Vec(IDL.Text),
  });
  const Result_30 = IDL.Variant({ 'ok' : PTWMasterData, 'err' : IDL.Text });
  const Result_29 = IDL.Variant({
    'ok' : IDL.Record({
      'complianceRate' : IDL.Nat,
      'issuanceCount' : IDL.Nat,
      'lowStockItems' : IDL.Nat,
      'totalItems' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const Result_28 = IDL.Variant({
    'ok' : IDL.Record({
      'byType' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
      'avgCycleTimeDays' : IDL.Float64,
      'cancelledThisMonth' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const PTWExtensionView = IDL.Record({
    'isCancelled' : IDL.Bool,
    'toolboxAttendees' : IDL.Vec(EmployeeId),
    'requiresLOTO' : IDL.Bool,
    'permitNumber' : IDL.Text,
    'cancellationReason' : IDL.Opt(IDL.Text),
    'gasTestCO' : IDL.Opt(IDL.Float64),
    'gasTestO2' : IDL.Opt(IDL.Float64),
    'createdAt' : Timestamp,
    'linkedJsaNumber' : IDL.Opt(IDL.Text),
    'cancelledAt' : IDL.Opt(Timestamp),
    'cancelledBy' : IDL.Opt(EmployeeId),
    'gasTestH2S' : IDL.Opt(IDL.Float64),
    'gasTestLEL' : IDL.Opt(IDL.Float64),
    'extensions' : IDL.Vec(PermitExtension),
    'gasTestPassed' : IDL.Bool,
    'linkedHiraNumber' : IDL.Opt(IDL.Text),
    'emergencyRescueDesc' : IDL.Opt(IDL.Text),
    'emergencyRescuePlan' : IDL.Bool,
    'toolboxTalkDone' : IDL.Bool,
  });
  const Result_27 = IDL.Variant({
    'ok' : IDL.Opt(PTWExtensionView),
    'err' : IDL.Text,
  });
  const Result_26 = IDL.Variant({
    'ok' : IDL.Vec(
      IDL.Record({
        'severity' : IDL.Text,
        'recommendation' : IDL.Text,
        'driver' : IDL.Text,
      })
    ),
    'err' : IDL.Text,
  });
  const Result_25 = IDL.Variant({
    'ok' : IDL.Vec(RiskScoreView),
    'err' : IDL.Text,
  });
  const Result_24 = IDL.Variant({
    'ok' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'err' : IDL.Text,
  });
  const PPEConditionIssue = IDL.Variant({
    'New' : IDL.Null,
    'Reissued' : IDL.Null,
  });
  const AuditAction = IDL.Variant({
    'Login' : IDL.Null,
    'Deactivated' : IDL.Null,
    'Reactivated' : IDL.Null,
    'Closed' : IDL.Null,
    'PasswordChanged' : IDL.Null,
    'Updated' : IDL.Null,
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Logout' : IDL.Null,
    'PasswordReset' : IDL.Null,
    'Created' : IDL.Null,
  });
  const AuditEntry = IDL.Record({
    'id' : IDL.Nat,
    'action' : AuditAction,
    'actorName' : IDL.Text,
    'actorRole' : Role,
    'actorId' : EmployeeId,
    'detail' : IDL.Text,
    'timestamp' : Timestamp,
    'module' : IDL.Text,
    'recordRef' : IDL.Text,
  });
  const Result_22 = IDL.Variant({
    'ok' : IDL.Vec(AuditEntry),
    'err' : IDL.Text,
  });
  const CAPAStatus = IDL.Variant({
    'Open' : IDL.Null,
    'Closed' : IDL.Null,
    'Overdue' : IDL.Null,
    'InProgress' : IDL.Null,
  });
  const CAPAView = IDL.Record({
    'id' : IDL.Nat,
    'status' : CAPAStatus,
    'actionOwnerId' : EmployeeId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'closedAt' : IDL.Opt(Timestamp),
    'actionOwnerName' : IDL.Text,
    'incidentNumber' : IDL.Text,
  });
  const Result_21 = IDL.Variant({ 'ok' : IDL.Vec(CAPAView), 'err' : IDL.Text });
  const Result_20 = IDL.Variant({
    'ok' : IDL.Vec(CAPA2View),
    'err' : IDL.Text,
  });
  const Result_19 = IDL.Variant({
    'ok' : IDL.Vec(ContractorView),
    'err' : IDL.Text,
  });
  const Result_18 = IDL.Variant({
    'ok' : IDL.Vec(EmployeeView),
    'err' : IDL.Text,
  });
  const Result_17 = IDL.Variant({ 'ok' : IDL.Vec(HIRAView), 'err' : IDL.Text });
  const Result_16 = IDL.Variant({
    'ok' : IDL.Vec(IncidentView),
    'err' : IDL.Text,
  });
  const Result_15 = IDL.Variant({ 'ok' : IDL.Vec(JSAView), 'err' : IDL.Text });
  const Result_14 = IDL.Variant({ 'ok' : IDL.Vec(LOTOView), 'err' : IDL.Text });
  const Result_13 = IDL.Variant({
    'ok' : IDL.Vec(ObservationView),
    'err' : IDL.Text,
  });
  const Result_12 = IDL.Variant({
    'ok' : IDL.Vec(PermitToWorkView),
    'err' : IDL.Text,
  });
  const PPEInventoryView = IDL.Record({
    'itemId' : IDL.Text,
    'quantityInStock' : IDL.Int,
    'lastUpdated' : Timestamp,
    'minStockLevel' : IDL.Nat,
  });
  const Result_11 = IDL.Variant({
    'ok' : IDL.Vec(PPEInventoryView),
    'err' : IDL.Text,
  });
  const PPEIssuance = IDL.Record({
    'issueDate' : IDL.Text,
    'itemId' : IDL.Text,
    'createdAt' : Timestamp,
    'size' : IDL.Text,
    'employeeId' : EmployeeId,
    'quantity' : IDL.Nat,
    'issuanceId' : IDL.Text,
    'condition' : PPEConditionIssue,
  });
  const Result_10 = IDL.Variant({
    'ok' : IDL.Vec(PPEIssuance),
    'err' : IDL.Text,
  });
  const PPEItem = IDL.Record({
    'itemId' : IDL.Text,
    'createdAt' : Timestamp,
    'size' : IDL.Text,
    'shelfLifeMonths' : IDL.Nat,
    'itemName' : IDL.Text,
    'itemType' : IDL.Text,
    'standard' : IDL.Text,
  });
  const Result_9 = IDL.Variant({ 'ok' : IDL.Vec(PPEItem), 'err' : IDL.Text });
  const Result_8 = IDL.Variant({
    'ok' : IDL.Vec(TrainingView),
    'err' : IDL.Text,
  });
  const Result_7 = IDL.Variant({ 'ok' : IDL.Vec(UserView), 'err' : IDL.Text });
  const Result_6 = IDL.Variant({
    'ok' : IDL.Record({ 'token' : IDL.Text, 'mustChangePassword' : IDL.Bool }),
    'err' : IDL.Text,
  });
  const PPEInspectionCondition = IDL.Variant({
    'Good' : IDL.Null,
    'Replace' : IDL.Null,
    'Damaged' : IDL.Null,
  });
  const CreateIncidentInput = IDL.Record({
    'description' : IDL.Text,
    'capaActionOwnerId' : EmployeeId,
    'capaDeadline' : IDL.Text,
    'injuredPersonCode' : IDL.Opt(IDL.Text),
    'severity' : Severity,
    'department' : IDL.Text,
    'location' : IDL.Text,
    'incidentDate' : IDL.Text,
    'incidentType' : IncidentType,
  });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  
  return IDL.Service({
    'acknowledgeObservation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'actOnHIRA' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [Result_1],
        [],
      ),
    'actOnJSA' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [Result_1],
        [],
      ),
    'activateLoto' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'addAirEmission' : IDL.Func(
        [IDL.Text, AddAirEmissionInput],
        [Result_1],
        [],
      ),
    'addCarbonEntry' : IDL.Func([IDL.Text, AddCarbonInput], [Result_1], []),
    'addContractorDocument' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'addContractorEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, ContractorEmployee],
        [Result_1],
        [],
      ),
    'addEffluentEntry' : IDL.Func([IDL.Text, AddEffluentInput], [Result_1], []),
    'addEmployee' : IDL.Func([IDL.Text, AddEmployeeInput], [Result_43], []),
    'addEnergyEntry' : IDL.Func([IDL.Text, AddEnergyInput], [Result_1], []),
    'addHazardRow' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          HazardType,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(EmployeeId),
        ],
        [Result_1],
        [],
      ),
    'addWasteEntry' : IDL.Func([IDL.Text, AddWasteInput], [Result_1], []),
    'addWaterEntry' : IDL.Func([IDL.Text, AddWaterInput], [Result_1], []),
    'answerRiskQuery' : IDL.Func([IDL.Text, IDL.Text], [Result_5], ['query']),
    'approvePTWAreaInCharge' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Result_1],
        [],
      ),
    'approvePTWFinalIssuer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'approvePTWHOD' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Result_1],
        [],
      ),
    'approvePTWIsolationAuthority' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Result_1],
        [],
      ),
    'approvePTWSafetyOfficer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Result_1],
        [],
      ),
    'calculateRiskScore' : IDL.Func([IDL.Text], [Result_51], []),
    'cancelLoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_1], []),
    'cancelPermit' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_1], []),
    'changePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_1], []),
    'checkAndUpdateDocumentStatuses' : IDL.Func([], [], []),
    'checkOverdueCapas' : IDL.Func([], [], []),
    'closeCAPA' : IDL.Func([IDL.Text, IDL.Nat], [Result_1], []),
    'closeObservation' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'closePTW' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'completeLoto' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'createCapa2' : IDL.Func([IDL.Text, CreateCAPAInput], [Result_5], []),
    'createContractor' : IDL.Func(
        [IDL.Text, CreateContractorInput],
        [Result_5],
        [],
      ),
    'createHIRA' : IDL.Func([IDL.Text, CreateHIRAInput], [Result_5], []),
    'createJSA' : IDL.Func([IDL.Text, CreateJSAInput], [Result_5], []),
    'createLoto' : IDL.Func([IDL.Text, CreateLOTOInput], [Result_5], []),
    'createObservation' : IDL.Func(
        [IDL.Text, CreateObservationInput],
        [Result_5],
        [],
      ),
    'createOrUpdatePtwExtension' : IDL.Func(
        [IDL.Text, IDL.Text, PTWExtension],
        [Result_1],
        [],
      ),
    'createPTW' : IDL.Func([IDL.Text, CreatePermitInput], [Result_5], []),
    'createPpeItem' : IDL.Func([IDL.Text, CreatePPEItemInput], [Result_5], []),
    'createTraining' : IDL.Func(
        [IDL.Text, CreateTrainingInput],
        [Result_23],
        [],
      ),
    'createUser' : IDL.Func([IDL.Text, CreateUserInput], [Result], []),
    'extendPermit' : IDL.Func(
        [IDL.Text, IDL.Text, Timestamp, IDL.Text],
        [Result_1],
        [],
      ),
    'getBbsStats' : IDL.Func([IDL.Text], [Result_50], ['query']),
    'getCapa2' : IDL.Func([IDL.Text, IDL.Text], [Result_49], ['query']),
    'getCapa2Stats' : IDL.Func([IDL.Text], [Result_48], ['query']),
    'getContractor' : IDL.Func([IDL.Text, IDL.Text], [Result_47], ['query']),
    'getContractorStats' : IDL.Func([IDL.Text], [Result_46], ['query']),
    'getDepartments' : IDL.Func([IDL.Text], [Result_36], ['query']),
    'getDeptOHSEScores' : IDL.Func([IDL.Text], [Result_45], ['query']),
    'getDeptRiskBreakdown' : IDL.Func([IDL.Text], [Result_44], ['query']),
    'getEmployee' : IDL.Func([IDL.Text, IDL.Text], [Result_43], ['query']),
    'getEsgData' : IDL.Func([IDL.Text], [Result_42], ['query']),
    'getEsgStats' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
        [Result_41],
        ['query'],
      ),
    'getHIRA' : IDL.Func([IDL.Text, IDL.Text], [Result_40], ['query']),
    'getIncident' : IDL.Func([IDL.Text, IDL.Text], [Result_4], ['query']),
    'getIncidentTrend' : IDL.Func([IDL.Text, IDL.Nat], [Result_39], ['query']),
    'getJSA' : IDL.Func([IDL.Text, IDL.Text], [Result_38], ['query']),
    'getKPISummary' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [Result_37],
        ['query'],
      ),
    'getLocations' : IDL.Func([IDL.Text], [Result_36], ['query']),
    'getLoto' : IDL.Func([IDL.Text, IDL.Text], [Result_35], ['query']),
    'getLotoStats' : IDL.Func([IDL.Text], [Result_34], ['query']),
    'getNotifications' : IDL.Func([IDL.Text], [Result_33], ['query']),
    'getObservation' : IDL.Func([IDL.Text, IDL.Text], [Result_32], ['query']),
    'getPTW' : IDL.Func([IDL.Text, IDL.Text], [Result_31], ['query']),
    'getPTWMasterData' : IDL.Func([IDL.Text], [Result_30], ['query']),
    'getPpeStats' : IDL.Func([IDL.Text], [Result_29], ['query']),
    'getPtwDashboardStats' : IDL.Func([IDL.Text], [Result_28], ['query']),
    'getPtwExtension' : IDL.Func([IDL.Text, IDL.Text], [Result_27], ['query']),
    'getRiskRecommendations' : IDL.Func([IDL.Text], [Result_26], ['query']),
    'getRiskScoreHistory' : IDL.Func([IDL.Text], [Result_25], ['query']),
    'getRiskScoreTrend' : IDL.Func([IDL.Text], [Result_24], ['query']),
    'getTraining' : IDL.Func([IDL.Text, IDL.Text], [Result_23], ['query']),
    'issuePpe' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, PPEConditionIssue],
        [Result_5],
        [],
      ),
    'linkContractorToPtw' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'listAuditEntries' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(Timestamp), IDL.Opt(Timestamp)],
        [Result_22],
        ['query'],
      ),
    'listCAPAs' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [Result_21],
        ['query'],
      ),
    'listCapa2s' : IDL.Func([IDL.Text], [Result_20], ['query']),
    'listContractors' : IDL.Func([IDL.Text], [Result_19], ['query']),
    'listEmployees' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(EmployeeStatus),
          IDL.Opt(IDL.Text),
        ],
        [Result_18],
        ['query'],
      ),
    'listHIRAs' : IDL.Func([IDL.Text], [Result_17], ['query']),
    'listIncidents' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IncidentType),
          IDL.Opt(Severity),
          IDL.Opt(IncidentStatus),
          IDL.Opt(IDL.Text),
        ],
        [Result_16],
        ['query'],
      ),
    'listJSAs' : IDL.Func([IDL.Text], [Result_15], ['query']),
    'listLotos' : IDL.Func([IDL.Text], [Result_14], ['query']),
    'listObservations' : IDL.Func([IDL.Text], [Result_13], ['query']),
    'listPTWs' : IDL.Func(
        [IDL.Text, IDL.Opt(PTWStatus), IDL.Opt(PermitType)],
        [Result_12],
        ['query'],
      ),
    'listPpeInventory' : IDL.Func([IDL.Text], [Result_11], ['query']),
    'listPpeIssuances' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat)],
        [Result_10],
        ['query'],
      ),
    'listPpeItems' : IDL.Func([IDL.Text], [Result_9], ['query']),
    'listTrainings' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(TrainingType)],
        [Result_8],
        ['query'],
      ),
    'listUsers' : IDL.Func(
        [IDL.Text, IDL.Opt(Role), IDL.Opt(IDL.Text), IDL.Opt(UserStatus)],
        [Result_7],
        ['query'],
      ),
    'login' : IDL.Func([EmployeeId, IDL.Text], [Result_6], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'markAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, AttendanceStatus],
        [Result_1],
        [],
      ),
    'markNotifRead' : IDL.Func([IDL.Text, IDL.Nat], [Result_1], []),
    'recordContractorPerformance' : IDL.Func(
        [IDL.Text, IDL.Text, ContractorPerformance],
        [Result_1],
        [],
      ),
    'recordEnergisation' : IDL.Func(
        [IDL.Text, IDL.Text, EnergisationRecord],
        [Result_1],
        [],
      ),
    'recordInduction' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [Result_5],
        [],
      ),
    'recordJSABriefing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(EmployeeId)],
        [Result_1],
        [],
      ),
    'recordPpeInspection' : IDL.Func(
        [IDL.Text, IDL.Text, PPEInspectionCondition, IDL.Text, IDL.Text],
        [Result_5],
        [],
      ),
    'recordToolboxTalk' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(EmployeeId)],
        [Result_1],
        [],
      ),
    'rejectPTW' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_1], []),
    'reportIncident' : IDL.Func(
        [IDL.Text, CreateIncidentInput],
        [Result_4],
        [],
      ),
    'resetPassword' : IDL.Func(
        [IDL.Text, EmployeeId, IDL.Text],
        [Result_1],
        [],
      ),
    'setPtwGasTest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [Result_3],
        [],
      ),
    'setUserStatus' : IDL.Func(
        [IDL.Text, EmployeeId, UserStatus],
        [Result_1],
        [],
      ),
    'submitCapa2ForVerification' : IDL.Func(
        [IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'submitHIRAForApproval' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'submitJSAForApproval' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'submitPTW' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Result_1], []),
    'suspendPTW' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_1], []),
    'unreadNotifCount' : IDL.Func([IDL.Text], [Result_2], ['query']),
    'updateCapa2Progress' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result_1],
        [],
      ),
    'updateContractorStatus' : IDL.Func(
        [IDL.Text, IDL.Text, ContractorStatus],
        [Result_1],
        [],
      ),
    'updateIncidentStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IncidentStatus, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'updateLockStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, LockEntryStatus],
        [Result_1],
        [],
      ),
    'updatePpeInventory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Nat],
        [Result_1],
        [],
      ),
    'verifyCapa2' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [Result_1],
        [],
      ),
    'whoAmI' : IDL.Func([IDL.Text], [Result], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };