/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddAirEmissionInput {
  'value' : number,
  'source' : AirEmissionSource,
  'unit' : string,
  'pollutant' : AirPollutant,
  'measurementDate' : string,
  'department' : string,
  'regulatoryLimit' : number,
}
export interface AddCarbonInput {
  'month' : bigint,
  'co2eTonnes' : number,
  'year' : bigint,
  'description' : string,
  'scope' : CarbonScope,
}
export interface AddEffluentInput {
  'samplingDate' : string,
  'value' : number,
  'parameter' : EffluentParameter,
  'effluentType' : EffluentType,
  'department' : string,
  'regulatoryLimit' : number,
}
export interface AddEmployeeInput {
  'contact' : string,
  'dateOfBirth' : string,
  'designation' : string,
  'site' : string,
  'joiningDate' : string,
  'fullName' : string,
  'email' : string,
  'employmentType' : EmploymentType,
  'department' : string,
}
export interface AddEnergyInput {
  'month' : bigint,
  'carbonEquivalent' : number,
  'unit' : string,
  'year' : bigint,
  'target' : number,
  'energyType' : EnergyType,
  'department' : string,
  'consumption' : number,
}
export interface AddWasteInput {
  'wasteType' : WasteType,
  'disposalMethod' : string,
  'unit' : string,
  'manifestNumber' : string,
  'quantity' : number,
  'department' : string,
  'disposalDate' : string,
  'contractorName' : string,
}
export interface AddWaterInput {
  'month' : bigint,
  'source' : WaterSource,
  'year' : bigint,
  'target' : number,
  'department' : string,
  'consumption' : number,
}
export interface AirEmissionEntry {
  'value' : number,
  'source' : AirEmissionSource,
  'createdAt' : Timestamp,
  'unit' : string,
  'pollutant' : AirPollutant,
  'isExceeded' : boolean,
  'measurementDate' : string,
  'department' : string,
  'regulatoryLimit' : number,
  'loggedBy' : EmployeeId,
}
export type AirEmissionSource = { 'Stack' : null } |
  { 'Vehicle' : null } |
  { 'Fugitive' : null };
export type AirPollutant = { 'CO2' : null } |
  { 'NOx' : null } |
  { 'SOx' : null } |
  { 'VOC' : null } |
  { 'PM10' : null };
export interface ApprovalStepView {
  'approverId' : EmployeeId,
  'role' : Role,
  'approverName' : string,
  'approved' : [] | [boolean],
  'actionAt' : [] | [Timestamp],
  'remarks' : string,
}
export type AttendanceStatus = { 'Present' : null } |
  { 'Absent' : null };
export type AuditAction = { 'Login' : null } |
  { 'Deactivated' : null } |
  { 'Reactivated' : null } |
  { 'Closed' : null } |
  { 'PasswordChanged' : null } |
  { 'Updated' : null } |
  { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Logout' : null } |
  { 'PasswordReset' : null } |
  { 'Created' : null };
export interface AuditEntry {
  'id' : bigint,
  'action' : AuditAction,
  'actorName' : string,
  'actorRole' : Role,
  'actorId' : EmployeeId,
  'detail' : string,
  'timestamp' : Timestamp,
  'module' : string,
  'recordRef' : string,
}
export interface CAPA2View {
  'status' : CAPAStatus2,
  'rootCauseCat' : RootCauseCat,
  'source' : CAPASource2,
  'createdAt' : Timestamp,
  'findingDescription' : string,
  'verifiedByEmpId' : [] | [EmployeeId],
  'updatedAt' : Timestamp,
  'progressUpdate' : string,
  'completionEvidence' : [] | [string],
  'targetDate' : string,
  'linkedRecordNumber' : string,
  'isOverdue' : boolean,
  'capaType' : CAPAType,
  'priority' : CAPAPriority,
  'actionDescription' : string,
  'actionOwnerEmpId' : EmployeeId,
  'department' : string,
  'rootCauseDesc' : string,
  'verifiedAt' : [] | [Timestamp],
  'capaNumber' : string,
}
export type CAPAPriority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Critical' : null };
export type CAPASource2 = { 'JSA' : null } |
  { 'HIRA' : null } |
  { 'Incident' : null } |
  { 'Observation' : null } |
  { 'Audit' : null } |
  { 'Manual' : null };
export type CAPAStatus = { 'Open' : null } |
  { 'Closed' : null } |
  { 'Overdue' : null } |
  { 'InProgress' : null };
export type CAPAStatus2 = { 'Open' : null } |
  { 'Closed' : null } |
  { 'PendingVerification' : null } |
  { 'Overdue' : null } |
  { 'InProgress' : null };
export type CAPAType = { 'Corrective' : null } |
  { 'Preventive' : null };
export interface CAPAView {
  'id' : bigint,
  'status' : CAPAStatus,
  'actionOwnerId' : EmployeeId,
  'createdAt' : Timestamp,
  'description' : string,
  'deadline' : string,
  'closedAt' : [] | [Timestamp],
  'actionOwnerName' : string,
  'incidentNumber' : string,
}
export interface CarbonEntry {
  'month' : bigint,
  'co2eTonnes' : number,
  'createdAt' : Timestamp,
  'year' : bigint,
  'description' : string,
  'scope' : CarbonScope,
  'loggedBy' : EmployeeId,
}
export type CarbonScope = { 'Scope1' : null } |
  { 'Scope2' : null } |
  { 'Scope3' : null };
export type CertificateStatus = { 'Valid' : null } |
  { 'ExpiringSoon' : null } |
  { 'Expired' : null };
export type ContractorDocStatus = { 'Expiring' : null } |
  { 'Valid' : null } |
  { 'Expired' : null };
export interface ContractorDocView {
  'status' : ContractorDocStatus,
  'expiryDate' : string,
  'docType' : string,
  'uploadedAt' : Timestamp,
}
export interface ContractorEmployee {
  'trade' : string,
  'inductionStatus' : InductionStatus,
  'inductionDate' : [] | [string],
  'idNumber' : string,
  'empName' : string,
  'certificateNumber' : [] | [string],
}
export interface ContractorEmployeeView {
  'trade' : string,
  'inductionStatus' : InductionStatus,
  'inductionDate' : [] | [string],
  'idNumber' : string,
  'empName' : string,
  'certificateNumber' : [] | [string],
}
export interface ContractorPerformance {
  'evaluatedAt' : Timestamp,
  'evaluatedBy' : EmployeeId,
  'ptwCompliance' : number,
  'overallRating' : PerformanceRating,
  'safetyScore' : bigint,
  'incidentCount' : bigint,
  'nearMissCount' : bigint,
  'trainingCompliance' : number,
}
export type ContractorStatus = { 'Active' : null } |
  { 'Blacklisted' : null } |
  { 'Expired' : null };
export interface ContractorView {
  'status' : ContractorStatus,
  'documents' : Array<ContractorDocView>,
  'employees' : Array<ContractorEmployeeView>,
  'createdAt' : Timestamp,
  'contactPerson' : string,
  'contractorId' : string,
  'registrationNumber' : string,
  'email' : string,
  'contractEndDate' : string,
  'updatedAt' : Timestamp,
  'performance' : [] | [ContractorPerformance],
  'companyName' : string,
  'phone' : string,
  'contractStartDate' : string,
  'typeOfWork' : string,
  'linkedPtwNumbers' : Array<string>,
}
export interface CreateCAPAInput {
  'rootCauseCat' : RootCauseCat,
  'source' : CAPASource2,
  'findingDescription' : string,
  'targetDate' : string,
  'linkedRecordNumber' : string,
  'capaType' : CAPAType,
  'priority' : CAPAPriority,
  'actionDescription' : string,
  'actionOwnerEmpId' : EmployeeId,
  'department' : string,
  'rootCauseDesc' : string,
}
export interface CreateContractorInput {
  'contactPerson' : string,
  'registrationNumber' : string,
  'email' : string,
  'contractEndDate' : string,
  'companyName' : string,
  'phone' : string,
  'contractStartDate' : string,
  'typeOfWork' : string,
}
export interface CreateHIRAInput {
  'responsibleEmpId' : [] | [EmployeeId],
  'area' : string,
  'taskDescription' : string,
  'reviewDate' : string,
  'department' : string,
  'location' : string,
}
export interface CreateIncidentInput {
  'description' : string,
  'capaActionOwnerId' : EmployeeId,
  'capaDeadline' : string,
  'injuredPersonCode' : [] | [string],
  'severity' : Severity,
  'department' : string,
  'location' : string,
  'incidentDate' : string,
  'incidentType' : IncidentType,
}
export interface CreateJSAInput {
  'linkedPtwNumber' : [] | [string],
  'helmetRequired' : boolean,
  'analysisDate' : string,
  'area' : string,
  'faceShield' : boolean,
  'emergencyContacts' : string,
  'jobTitle' : string,
  'harness' : boolean,
  'respirator' : boolean,
  'safetyShoes' : boolean,
  'gloves' : boolean,
  'goggles' : boolean,
  'department' : string,
  'location' : string,
}
export interface CreateLOTOInput {
  'equipmentName' : string,
  'workDescription' : string,
  'tagNumber' : string,
  'startDateTime' : Timestamp,
}
export interface CreateObservationInput {
  'area' : string,
  'description' : string,
  'photoUrl' : [] | [string],
  'immediateAction' : string,
  'obsType' : ObservationType,
  'severity' : ObservationSeverity,
  'department' : string,
  'dateTime' : Timestamp,
  'location' : string,
}
export interface CreatePPEItemInput {
  'size' : string,
  'shelfLifeMonths' : bigint,
  'itemName' : string,
  'itemType' : string,
  'standard' : string,
}
export interface CreatePTWInput {
  'ppeRequired' : Array<string>,
  'riskAssessed' : boolean,
  'workDescription' : string,
  'permitType' : PermitType,
  'endDateTime' : string,
  'startDateTime' : string,
  'location' : string,
  'contractorTeam' : string,
}
export interface CreateTrainingInput {
  'attendeeCodes' : Array<string>,
  'name' : string,
  'trainer' : string,
  'trainingDate' : string,
  'trainingType' : TrainingType,
  'frequency' : TrainingFrequency,
  'department' : string,
}
export interface CreateUserInput {
  'password' : string,
  'designation' : string,
  'role' : Role,
  'fullName' : string,
  'email' : string,
  'employeeId' : EmployeeId,
  'department' : string,
}
export interface DeptOHSEScore { 'score' : number, 'department' : string }
export interface EffluentEntry {
  'samplingDate' : string,
  'isCompliant' : boolean,
  'value' : number,
  'parameter' : EffluentParameter,
  'createdAt' : Timestamp,
  'effluentType' : EffluentType,
  'department' : string,
  'regulatoryLimit' : number,
  'loggedBy' : EmployeeId,
}
export type EffluentParameter = { 'PH' : null } |
  { 'BOD' : null } |
  { 'COD' : null } |
  { 'TSS' : null } |
  { 'HeavyMetals' : null };
export type EffluentType = { 'Domestic' : null } |
  { 'Stormwater' : null } |
  { 'Process' : null };
export type EmployeeId = bigint;
export type EmployeeStatus = { 'Inactive' : null } |
  { 'Active' : null } |
  { 'Resigned' : null };
export interface EmployeeView {
  'contact' : string,
  'dateOfBirth' : string,
  'designation' : string,
  'createdAt' : Timestamp,
  'site' : string,
  'joiningDate' : string,
  'fullName' : string,
  'email' : string,
  'employmentType' : EmploymentType,
  'empCode' : string,
  'department' : string,
  'empStatus' : EmployeeStatus,
}
export type EmploymentType = { 'Contract' : null } |
  { 'FullTime' : null } |
  { 'Temporary' : null };
export interface EnergyEntry {
  'month' : bigint,
  'carbonEquivalent' : number,
  'createdAt' : Timestamp,
  'unit' : string,
  'year' : bigint,
  'target' : number,
  'energyType' : EnergyType,
  'department' : string,
  'loggedBy' : EmployeeId,
  'consumption' : number,
}
export type EnergySourceLOTO = { 'Chemical' : null } |
  { 'Hydraulic' : null } |
  { 'Gravitational' : null } |
  { 'Mechanical' : null } |
  { 'Thermal' : null } |
  { 'Pneumatic' : null } |
  { 'Electrical' : null };
export type EnergyType = { 'Gas' : null } |
  { 'LPG' : null } |
  { 'Renewable' : null } |
  { 'Electricity' : null } |
  { 'Diesel' : null };
export type HIRAStatus = { 'UnderReview' : null } |
  { 'Approved' : null } |
  { 'Draft' : null } |
  { 'Expired' : null };
export interface HIRAView {
  'status' : HIRAStatus,
  'responsibleEmpId' : [] | [EmployeeId],
  'soEmpId' : [] | [EmployeeId],
  'linkedPtwNumber' : [] | [string],
  'aicAt' : [] | [Timestamp],
  'hodAt' : [] | [Timestamp],
  'hazards' : Array<HazardRow>,
  'aicRemarks' : [] | [string],
  'area' : string,
  'hodEmpId' : [] | [EmployeeId],
  'soRemarks' : [] | [string],
  'createdAt' : Timestamp,
  'createdBy' : EmployeeId,
  'soAt' : [] | [Timestamp],
  'aicEmpId' : [] | [EmployeeId],
  'taskDescription' : string,
  'reviewDate' : string,
  'approvalStep' : bigint,
  'updatedAt' : Timestamp,
  'hodRemarks' : [] | [string],
  'hiraNumber' : string,
  'department' : string,
  'location' : string,
}
export interface HazardRow {
  'responsibleEmpId' : [] | [EmployeeId],
  'hazardType' : HazardType,
  'hazardDescription' : string,
  'residualRiskScore' : bigint,
  'additionalControls' : string,
  'severity' : bigint,
  'existingControls' : string,
  'likelihood' : bigint,
  'riskLevel' : RiskLevel,
  'riskScore' : bigint,
  'hazardId' : string,
}
export type HazardType = { 'Ergonomic' : null } |
  { 'Chemical' : null } |
  { 'Biological' : null } |
  { 'Psychological' : null } |
  { 'Physical' : null } |
  { 'Environmental' : null };
export type IncidentStatus = { 'UnderInvestigation' : null } |
  { 'Open' : null } |
  { 'Closed' : null } |
  { 'CAPAPending' : null };
export type IncidentType = { 'LTI' : null } |
  { 'UnsafeAct' : null } |
  { 'UnsafeCondition' : null } |
  { 'NearMiss' : null } |
  { 'Fatal' : null } |
  { 'FirstAid' : null };
export interface IncidentView {
  'status' : IncidentStatus,
  'reportedByName' : string,
  'reportedById' : EmployeeId,
  'createdAt' : Timestamp,
  'description' : string,
  'closedAt' : [] | [Timestamp],
  'injuredPersonCode' : [] | [string],
  'incidentNumber' : string,
  'severity' : Severity,
  'department' : string,
  'correctiveAction' : string,
  'location' : string,
  'incidentDate' : string,
  'incidentType' : IncidentType,
  'rootCause' : string,
}
export type InductionStatus = { 'Fail' : null } |
  { 'Pass' : null } |
  { 'Pending' : null };
export interface IsolationPoint {
  'status' : IsolationPointStatus,
  'pointId' : string,
  'location' : string,
  'lockNumber' : string,
}
export type IsolationPointStatus = { 'Applied' : null } |
  { 'Removed' : null };
export type JSAStatus = { 'UnderReview' : null } |
  { 'Closed' : null } |
  { 'Active' : null } |
  { 'Approved' : null } |
  { 'Draft' : null };
export interface JSAStep {
  'stepNo' : bigint,
  'responsibleEmpId' : [] | [EmployeeId],
  'hazards' : string,
  'controls' : string,
  'description' : string,
  'riskLevel' : RiskLevel,
}
export interface JSAView {
  'status' : JSAStatus,
  'linkedPtwNumber' : [] | [string],
  'hodAt' : [] | [Timestamp],
  'helmetRequired' : boolean,
  'analysisDate' : string,
  'area' : string,
  'soRemarks' : [] | [string],
  'approvedBy' : [] | [EmployeeId],
  'createdAt' : Timestamp,
  'soAt' : [] | [Timestamp],
  'faceShield' : boolean,
  'emergencyContacts' : string,
  'reviewedBy' : [] | [EmployeeId],
  'preparedBy' : EmployeeId,
  'updatedAt' : Timestamp,
  'steps' : Array<JSAStep>,
  'jobTitle' : string,
  'briefingAttendees' : Array<EmployeeId>,
  'harness' : boolean,
  'respirator' : boolean,
  'jsaNumber' : string,
  'hodRemarks' : [] | [string],
  'safetyShoes' : boolean,
  'gloves' : boolean,
  'goggles' : boolean,
  'department' : string,
  'location' : string,
}
export interface KPISummary {
  'trainingCompliancePct' : number,
  'auditScorePct' : number,
  'trir' : number,
  'ptwCompliancePct' : number,
  'ltifr' : number,
  'openCAPAs' : bigint,
  'nearMissCount' : bigint,
  'totalIncidents' : bigint,
}
export type LOTOStatus = { 'Active' : null } |
  { 'Draft' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null };
export interface LOTOView {
  'status' : LOTOStatus,
  'reEnergizationChecklist' : Array<string>,
  'createdAt' : Timestamp,
  'createdBy' : EmployeeId,
  'equipmentName' : string,
  'lotoNumber' : string,
  'authorizedAt' : [] | [Timestamp],
  'workDescription' : string,
  'updatedAt' : Timestamp,
  'endDateTime' : [] | [Timestamp],
  'energySources' : Array<EnergySourceLOTO>,
  'lockRegister' : Array<LockEntryView>,
  'tagNumber' : string,
  'authorizedEmpIds' : Array<EmployeeId>,
  'isolationPoints' : Array<IsolationPoint>,
  'startDateTime' : Timestamp,
  'authorizedByEmpId' : [] | [EmployeeId],
  'procedureSteps' : Array<string>,
}
export type LockEntryStatus = { 'Applied' : null } |
  { 'Removed' : null };
export interface LockEntryView {
  'status' : LockEntryStatus,
  'assignedEmpId' : EmployeeId,
  'lockNumber' : string,
}
export interface MonthlyTrend {
  'month' : bigint,
  'year' : bigint,
  'incidentCount' : bigint,
}
export interface NotificationView {
  'id' : bigint,
  'link' : string,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'message' : string,
  'recipientId' : EmployeeId,
}
export type ObservationSeverity = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export type ObservationStatus = { 'UnderReview' : null } |
  { 'Open' : null } |
  { 'Closed' : null } |
  { 'CAPAPending' : null };
export type ObservationType = { 'UnsafeAct' : null } |
  { 'UnsafeCondition' : null } |
  { 'SafeAct' : null } |
  { 'PositiveReinforcement' : null } |
  { 'NearMiss' : null };
export interface ObservationView {
  'status' : ObservationStatus,
  'acknowledgedAt' : [] | [Timestamp],
  'acknowledgedBy' : [] | [EmployeeId],
  'linkedCapaId' : [] | [string],
  'area' : string,
  'createdAt' : Timestamp,
  'observerName' : string,
  'description' : string,
  'photoUrl' : [] | [string],
  'immediateAction' : string,
  'observerEmpId' : EmployeeId,
  'acknowledgeRemarks' : [] | [string],
  'obsType' : ObservationType,
  'severity' : ObservationSeverity,
  'department' : string,
  'dateTime' : Timestamp,
  'obsNumber' : string,
  'location' : string,
}
export type PPEConditionIssue = { 'New' : null } |
  { 'Reissued' : null };
export type PPEInspectionCondition = { 'Good' : null } |
  { 'Replace' : null } |
  { 'Damaged' : null };
export interface PPEInventoryView {
  'itemId' : string,
  'quantityInStock' : bigint,
  'lastUpdated' : Timestamp,
  'minStockLevel' : bigint,
}
export interface PPEIssuance {
  'issueDate' : string,
  'itemId' : string,
  'createdAt' : Timestamp,
  'size' : string,
  'employeeId' : EmployeeId,
  'quantity' : bigint,
  'issuanceId' : string,
  'condition' : PPEConditionIssue,
}
export interface PPEItem {
  'itemId' : string,
  'createdAt' : Timestamp,
  'size' : string,
  'shelfLifeMonths' : bigint,
  'itemName' : string,
  'itemType' : string,
  'standard' : string,
}
export interface PTWExtension {
  'isCancelled' : boolean,
  'toolboxAttendees' : Array<EmployeeId>,
  'requiresLOTO' : boolean,
  'permitNumber' : string,
  'cancellationReason' : [] | [string],
  'gasTestCO' : [] | [number],
  'gasTestO2' : [] | [number],
  'createdAt' : Timestamp,
  'linkedJsaNumber' : [] | [string],
  'cancelledAt' : [] | [Timestamp],
  'cancelledBy' : [] | [EmployeeId],
  'gasTestH2S' : [] | [number],
  'gasTestLEL' : [] | [number],
  'extensions' : Array<PermitExtension>,
  'gasTestPassed' : boolean,
  'linkedHiraNumber' : [] | [string],
  'emergencyRescueDesc' : [] | [string],
  'emergencyRescuePlan' : boolean,
  'toolboxTalkDone' : boolean,
}
export interface PTWExtensionView {
  'isCancelled' : boolean,
  'toolboxAttendees' : Array<EmployeeId>,
  'requiresLOTO' : boolean,
  'permitNumber' : string,
  'cancellationReason' : [] | [string],
  'gasTestCO' : [] | [number],
  'gasTestO2' : [] | [number],
  'createdAt' : Timestamp,
  'linkedJsaNumber' : [] | [string],
  'cancelledAt' : [] | [Timestamp],
  'cancelledBy' : [] | [EmployeeId],
  'gasTestH2S' : [] | [number],
  'gasTestLEL' : [] | [number],
  'extensions' : Array<PermitExtension>,
  'gasTestPassed' : boolean,
  'linkedHiraNumber' : [] | [string],
  'emergencyRescueDesc' : [] | [string],
  'emergencyRescuePlan' : boolean,
  'toolboxTalkDone' : boolean,
}
export type PTWStatus = { 'PendingSafetyOfficer' : null } |
  { 'Closed' : null } |
  { 'Active' : null } |
  { 'Draft' : null } |
  { 'Rejected' : null } |
  { 'PendingAreaInCharge' : null } |
  { 'PendingHOD' : null } |
  { 'Completed' : null };
export interface PTWView {
  'status' : PTWStatus,
  'hodStep' : [] | [ApprovalStepView],
  'soStep' : [] | [ApprovalStepView],
  'permitNumber' : string,
  'rejectedRemarks' : string,
  'ppeRequired' : Array<string>,
  'createdAt' : Timestamp,
  'riskAssessed' : boolean,
  'workDescription' : string,
  'permitType' : PermitType,
  'closedAt' : [] | [Timestamp],
  'endDateTime' : string,
  'rejectedAt' : [] | [Timestamp],
  'requestedById' : EmployeeId,
  'requestedByName' : string,
  'startDateTime' : string,
  'location' : string,
  'contractorTeam' : string,
  'aicStep' : [] | [ApprovalStepView],
}
export type PerformanceRating = { 'Fair' : null } |
  { 'Good' : null } |
  { 'Poor' : null } |
  { 'Excellent' : null };
export interface PermitExtension {
  'newEndTime' : Timestamp,
  'originalEndTime' : Timestamp,
  'extendedAt' : Timestamp,
  'extendedBy' : EmployeeId,
  'reason' : string,
}
export type PermitType = { 'HotWork' : null } |
  { 'ElectricalIsolation' : null } |
  { 'ConfinedSpace' : null } |
  { 'WorkAtHeight' : null } |
  { 'Excavation' : null } |
  { 'ColdWork' : null };
export type Result = { 'ok' : UserView } |
  { 'err' : string };
export type Result_1 = { 'ok' : null } |
  { 'err' : string };
export type Result_10 = { 'ok' : Array<PPEIssuance> } |
  { 'err' : string };
export type Result_11 = { 'ok' : Array<PPEInventoryView> } |
  { 'err' : string };
export type Result_12 = { 'ok' : Array<PTWView> } |
  { 'err' : string };
export type Result_13 = { 'ok' : Array<ObservationView> } |
  { 'err' : string };
export type Result_14 = { 'ok' : Array<LOTOView> } |
  { 'err' : string };
export type Result_15 = { 'ok' : Array<JSAView> } |
  { 'err' : string };
export type Result_16 = { 'ok' : Array<IncidentView> } |
  { 'err' : string };
export type Result_17 = { 'ok' : Array<HIRAView> } |
  { 'err' : string };
export type Result_18 = { 'ok' : Array<EmployeeView> } |
  { 'err' : string };
export type Result_19 = { 'ok' : Array<ContractorView> } |
  { 'err' : string };
export type Result_2 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_20 = { 'ok' : Array<CAPA2View> } |
  { 'err' : string };
export type Result_21 = { 'ok' : Array<CAPAView> } |
  { 'err' : string };
export type Result_22 = { 'ok' : Array<AuditEntry> } |
  { 'err' : string };
export type Result_23 = { 'ok' : TrainingView } |
  { 'err' : string };
export type Result_24 = { 'ok' : Array<[string, bigint]> } |
  { 'err' : string };
export type Result_25 = { 'ok' : Array<RiskScoreView> } |
  { 'err' : string };
export type Result_26 = {
    'ok' : Array<
      { 'severity' : string, 'recommendation' : string, 'driver' : string }
    >
  } |
  { 'err' : string };
export type Result_27 = { 'ok' : [] | [PTWExtensionView] } |
  { 'err' : string };
export type Result_28 = {
    'ok' : {
      'byType' : Array<[string, bigint]>,
      'avgCycleTimeDays' : number,
      'cancelledThisMonth' : bigint,
    }
  } |
  { 'err' : string };
export type Result_29 = {
    'ok' : {
      'complianceRate' : bigint,
      'issuanceCount' : bigint,
      'lowStockItems' : bigint,
      'totalItems' : bigint,
    }
  } |
  { 'err' : string };
export type Result_3 = { 'ok' : boolean } |
  { 'err' : string };
export type Result_30 = { 'ok' : PTWView } |
  { 'err' : string };
export type Result_31 = { 'ok' : ObservationView } |
  { 'err' : string };
export type Result_32 = { 'ok' : Array<NotificationView> } |
  { 'err' : string };
export type Result_33 = {
    'ok' : {
      'active' : bigint,
      'completedThisMonth' : bigint,
      'overdue' : bigint,
    }
  } |
  { 'err' : string };
export type Result_34 = { 'ok' : LOTOView } |
  { 'err' : string };
export type Result_35 = { 'ok' : KPISummary } |
  { 'err' : string };
export type Result_36 = { 'ok' : JSAView } |
  { 'err' : string };
export type Result_37 = { 'ok' : Array<MonthlyTrend> } |
  { 'err' : string };
export type Result_38 = { 'ok' : HIRAView } |
  { 'err' : string };
export type Result_39 = {
    'ok' : {
      'complianceRate' : bigint,
      'carbonTotal' : number,
      'trendData' : Array<[string, number]>,
      'esgScore' : bigint,
      'waterTotal' : number,
      'wasteTotal' : number,
      'energyTotal' : number,
    }
  } |
  { 'err' : string };
export type Result_4 = { 'ok' : IncidentView } |
  { 'err' : string };
export type Result_40 = {
    'ok' : {
      'air' : Array<AirEmissionEntry>,
      'effluent' : Array<EffluentEntry>,
      'esgScore' : bigint,
      'carbon' : Array<CarbonEntry>,
      'waste' : Array<WasteEntry>,
      'water' : Array<WaterEntry>,
      'energy' : Array<EnergyEntry>,
    }
  } |
  { 'err' : string };
export type Result_41 = { 'ok' : EmployeeView } |
  { 'err' : string };
export type Result_42 = { 'ok' : Array<[string, bigint, string]> } |
  { 'err' : string };
export type Result_43 = { 'ok' : Array<DeptOHSEScore> } |
  { 'err' : string };
export type Result_44 = {
    'ok' : {
      'performanceSummary' : Array<[string, string]>,
      'incidentCount' : bigint,
      'activeCount' : bigint,
      'inductionCompliance' : bigint,
      'expiringDocs' : bigint,
    }
  } |
  { 'err' : string };
export type Result_45 = { 'ok' : ContractorView } |
  { 'err' : string };
export type Result_46 = {
    'ok' : {
      'byDept' : Array<[string, bigint]>,
      'closed' : bigint,
      'closureRate' : bigint,
      'total' : bigint,
      'open' : bigint,
      'overdue' : bigint,
      'avgDaysToClose' : number,
      'inProgress' : bigint,
      'bySource' : Array<[string, bigint]>,
    }
  } |
  { 'err' : string };
export type Result_47 = { 'ok' : CAPA2View } |
  { 'err' : string };
export type Result_48 = {
    'ok' : {
      'byDept' : Array<[string, bigint]>,
      'total' : bigint,
      'safe' : bigint,
      'unsafe' : bigint,
      'score' : bigint,
    }
  } |
  { 'err' : string };
export type Result_49 = { 'ok' : RiskScoreView } |
  { 'err' : string };
export type Result_5 = { 'ok' : string } |
  { 'err' : string };
export type Result_6 = {
    'ok' : { 'token' : string, 'mustChangePassword' : boolean }
  } |
  { 'err' : string };
export type Result_7 = { 'ok' : Array<UserView> } |
  { 'err' : string };
export type Result_8 = { 'ok' : Array<TrainingView> } |
  { 'err' : string };
export type Result_9 = { 'ok' : Array<PPEItem> } |
  { 'err' : string };
export type RiskLevel = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Critical' : null };
export interface RiskScoreView {
  'overallScore' : bigint,
  'calculatedAt' : Timestamp,
  'calculatedBy' : string,
  'unsafeObsCount' : bigint,
  'openHighCriticalIncidents' : bigint,
  'nearMissCount' : bigint,
  'trainingGapCount' : bigint,
  'departmentScores' : Array<[string, bigint]>,
  'riskLevel' : RiskLevel,
  'overdueCAPACount' : bigint,
}
export type Role = { 'HOD' : null } |
  { 'SystemAdmin' : null } |
  { 'ContractorAdmin' : null } |
  { 'Employee' : null } |
  { 'AreaInCharge' : null } |
  { 'SafetyOfficer' : null };
export type RootCauseCat = { 'ProcedureGap' : null } |
  { 'ManagementSystem' : null } |
  { 'HumanError' : null } |
  { 'TrainingGap' : null } |
  { 'Environmental' : null } |
  { 'EquipmentFailure' : null };
export type Severity = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Critical' : null };
export type Timestamp = bigint;
export interface TrainingAttendeeView {
  'certStatus' : [] | [CertificateStatus],
  'expiryDate' : [] | [string],
  'certificateId' : [] | [string],
  'attendance' : AttendanceStatus,
  'empCode' : string,
  'empName' : string,
}
export type TrainingFrequency = { 'OneTime' : null } |
  { 'ThreeYearly' : null } |
  { 'BiAnnual' : null } |
  { 'Annual' : null };
export type TrainingType = { 'Induction' : null } |
  { 'Regulatory' : null } |
  { 'OnTheJob' : null } |
  { 'Refresher' : null } |
  { 'External' : null };
export interface TrainingView {
  'name' : string,
  'createdAt' : Timestamp,
  'createdById' : EmployeeId,
  'trainingId' : string,
  'trainer' : string,
  'trainingDate' : string,
  'attendees' : Array<TrainingAttendeeView>,
  'trainingType' : TrainingType,
  'frequency' : TrainingFrequency,
  'department' : string,
}
export type UserStatus = { 'Inactive' : null } |
  { 'Active' : null };
export interface UserView {
  'status' : UserStatus,
  'designation' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'fullName' : string,
  'email' : string,
  'employeeId' : EmployeeId,
  'department' : string,
  'lastLogin' : [] | [Timestamp],
  'roles' : Array<Role>,
  'mustChangePassword' : boolean,
}
export interface WasteEntry {
  'wasteType' : WasteType,
  'disposalMethod' : string,
  'createdAt' : Timestamp,
  'unit' : string,
  'manifestNumber' : string,
  'quantity' : number,
  'department' : string,
  'disposalDate' : string,
  'loggedBy' : EmployeeId,
  'contractorName' : string,
}
export type WasteType = { 'Hazardous' : null } |
  { 'General' : null } |
  { 'Recyclable' : null } |
  { 'Scheduled' : null };
export interface WaterEntry {
  'month' : bigint,
  'source' : WaterSource,
  'createdAt' : Timestamp,
  'year' : bigint,
  'target' : number,
  'department' : string,
  'loggedBy' : EmployeeId,
  'consumption' : number,
}
export type WaterSource = { 'Recycled' : null } |
  { 'Groundwater' : null } |
  { 'Municipal' : null };
export interface _SERVICE {
  'acknowledgeObservation' : ActorMethod<[string, string, string], Result_1>,
  'actOnHIRA' : ActorMethod<[string, string, boolean, string], Result_1>,
  'actOnJSA' : ActorMethod<[string, string, boolean, string], Result_1>,
  'actOnPTW' : ActorMethod<[string, string, boolean, string], Result_1>,
  'activateLoto' : ActorMethod<[string, string], Result_1>,
  'addAirEmission' : ActorMethod<[string, AddAirEmissionInput], Result_1>,
  'addCarbonEntry' : ActorMethod<[string, AddCarbonInput], Result_1>,
  'addContractorDocument' : ActorMethod<
    [string, string, string, string],
    Result_1
  >,
  'addContractorEmployee' : ActorMethod<
    [string, string, ContractorEmployee],
    Result_1
  >,
  'addEffluentEntry' : ActorMethod<[string, AddEffluentInput], Result_1>,
  'addEmployee' : ActorMethod<[string, AddEmployeeInput], Result_41>,
  'addEnergyEntry' : ActorMethod<[string, AddEnergyInput], Result_1>,
  'addHazardRow' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      HazardType,
      bigint,
      bigint,
      string,
      string,
      bigint,
      [] | [EmployeeId],
    ],
    Result_1
  >,
  'addWasteEntry' : ActorMethod<[string, AddWasteInput], Result_1>,
  'addWaterEntry' : ActorMethod<[string, AddWaterInput], Result_1>,
  'answerRiskQuery' : ActorMethod<[string, string], Result_5>,
  'calculateRiskScore' : ActorMethod<[string], Result_49>,
  'cancelLoto' : ActorMethod<[string, string, string], Result_1>,
  'cancelPermit' : ActorMethod<[string, string, string], Result_1>,
  'changePassword' : ActorMethod<[string, string, string], Result_1>,
  'checkAndUpdateDocumentStatuses' : ActorMethod<[], undefined>,
  'checkOverdueCapas' : ActorMethod<[], undefined>,
  'closeCAPA' : ActorMethod<[string, bigint], Result_1>,
  'closeObservation' : ActorMethod<[string, string], Result_1>,
  'closePTW' : ActorMethod<[string, string], Result_1>,
  'completeLoto' : ActorMethod<[string, string], Result_1>,
  'createCapa2' : ActorMethod<[string, CreateCAPAInput], Result_5>,
  'createContractor' : ActorMethod<[string, CreateContractorInput], Result_5>,
  'createHIRA' : ActorMethod<[string, CreateHIRAInput], Result_5>,
  'createJSA' : ActorMethod<[string, CreateJSAInput], Result_5>,
  'createLoto' : ActorMethod<[string, CreateLOTOInput], Result_5>,
  'createObservation' : ActorMethod<[string, CreateObservationInput], Result_5>,
  'createOrUpdatePtwExtension' : ActorMethod<
    [string, string, PTWExtension],
    Result_1
  >,
  'createPTW' : ActorMethod<[string, CreatePTWInput], Result_30>,
  'createPpeItem' : ActorMethod<[string, CreatePPEItemInput], Result_5>,
  'createTraining' : ActorMethod<[string, CreateTrainingInput], Result_23>,
  'createUser' : ActorMethod<[string, CreateUserInput], Result>,
  'extendPermit' : ActorMethod<[string, string, Timestamp, string], Result_1>,
  'getBbsStats' : ActorMethod<[string], Result_48>,
  'getCapa2' : ActorMethod<[string, string], Result_47>,
  'getCapa2Stats' : ActorMethod<[string], Result_46>,
  'getContractor' : ActorMethod<[string, string], Result_45>,
  'getContractorStats' : ActorMethod<[string], Result_44>,
  'getDeptOHSEScores' : ActorMethod<[string], Result_43>,
  'getDeptRiskBreakdown' : ActorMethod<[string], Result_42>,
  'getEmployee' : ActorMethod<[string, string], Result_41>,
  'getEsgData' : ActorMethod<[string], Result_40>,
  'getEsgStats' : ActorMethod<
    [string, [] | [bigint], [] | [bigint], [] | [string]],
    Result_39
  >,
  'getHIRA' : ActorMethod<[string, string], Result_38>,
  'getIncident' : ActorMethod<[string, string], Result_4>,
  'getIncidentTrend' : ActorMethod<[string, bigint], Result_37>,
  'getJSA' : ActorMethod<[string, string], Result_36>,
  'getKPISummary' : ActorMethod<[string, [] | [string]], Result_35>,
  'getLoto' : ActorMethod<[string, string], Result_34>,
  'getLotoStats' : ActorMethod<[string], Result_33>,
  'getNotifications' : ActorMethod<[string], Result_32>,
  'getObservation' : ActorMethod<[string, string], Result_31>,
  'getPTW' : ActorMethod<[string, string], Result_30>,
  'getPpeStats' : ActorMethod<[string], Result_29>,
  'getPtwDashboardStats' : ActorMethod<[string], Result_28>,
  'getPtwExtension' : ActorMethod<[string, string], Result_27>,
  'getRiskRecommendations' : ActorMethod<[string], Result_26>,
  'getRiskScoreHistory' : ActorMethod<[string], Result_25>,
  'getRiskScoreTrend' : ActorMethod<[string], Result_24>,
  'getTraining' : ActorMethod<[string, string], Result_23>,
  'issuePpe' : ActorMethod<
    [string, bigint, string, string, bigint, PPEConditionIssue],
    Result_5
  >,
  'linkContractorToPtw' : ActorMethod<[string, string, string], Result_1>,
  'listAuditEntries' : ActorMethod<
    [string, [] | [string], [] | [Timestamp], [] | [Timestamp]],
    Result_22
  >,
  'listCAPAs' : ActorMethod<[string, [] | [string]], Result_21>,
  'listCapa2s' : ActorMethod<[string], Result_20>,
  'listContractors' : ActorMethod<[string], Result_19>,
  'listEmployees' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [string],
      [] | [EmployeeStatus],
      [] | [string],
    ],
    Result_18
  >,
  'listHIRAs' : ActorMethod<[string], Result_17>,
  'listIncidents' : ActorMethod<
    [
      string,
      [] | [IncidentType],
      [] | [Severity],
      [] | [IncidentStatus],
      [] | [string],
    ],
    Result_16
  >,
  'listJSAs' : ActorMethod<[string], Result_15>,
  'listLotos' : ActorMethod<[string], Result_14>,
  'listObservations' : ActorMethod<[string], Result_13>,
  'listPTWs' : ActorMethod<
    [string, [] | [PTWStatus], [] | [PermitType]],
    Result_12
  >,
  'listPpeInventory' : ActorMethod<[string], Result_11>,
  'listPpeIssuances' : ActorMethod<[string, [] | [bigint]], Result_10>,
  'listPpeItems' : ActorMethod<[string], Result_9>,
  'listTrainings' : ActorMethod<
    [string, [] | [string], [] | [TrainingType]],
    Result_8
  >,
  'listUsers' : ActorMethod<
    [string, [] | [Role], [] | [string], [] | [UserStatus]],
    Result_7
  >,
  'login' : ActorMethod<[EmployeeId, string], Result_6>,
  'logout' : ActorMethod<[string], undefined>,
  'markAttendance' : ActorMethod<
    [string, string, string, AttendanceStatus],
    Result_1
  >,
  'markNotifRead' : ActorMethod<[string, bigint], Result_1>,
  'recordContractorPerformance' : ActorMethod<
    [string, string, ContractorPerformance],
    Result_1
  >,
  'recordInduction' : ActorMethod<[string, string, string, boolean], Result_5>,
  'recordJSABriefing' : ActorMethod<
    [string, string, Array<EmployeeId>],
    Result_1
  >,
  'recordPpeInspection' : ActorMethod<
    [string, string, PPEInspectionCondition, string, string],
    Result_5
  >,
  'recordToolboxTalk' : ActorMethod<
    [string, string, Array<EmployeeId>],
    Result_1
  >,
  'reportIncident' : ActorMethod<[string, CreateIncidentInput], Result_4>,
  'resetPassword' : ActorMethod<[string, EmployeeId, string], Result_1>,
  'setPtwGasTest' : ActorMethod<
    [string, string, number, number, number, number],
    Result_3
  >,
  'setUserStatus' : ActorMethod<[string, EmployeeId, UserStatus], Result_1>,
  'submitCapa2ForVerification' : ActorMethod<[string, string], Result_1>,
  'submitHIRAForApproval' : ActorMethod<[string, string], Result_1>,
  'submitJSAForApproval' : ActorMethod<[string, string], Result_1>,
  'submitPTW' : ActorMethod<[string, string], Result_1>,
  'unreadNotifCount' : ActorMethod<[string], Result_2>,
  'updateCapa2Progress' : ActorMethod<
    [string, string, string, [] | [string]],
    Result_1
  >,
  'updateContractorStatus' : ActorMethod<
    [string, string, ContractorStatus],
    Result_1
  >,
  'updateIncidentStatus' : ActorMethod<
    [string, string, IncidentStatus, string, string],
    Result_1
  >,
  'updateLockStatus' : ActorMethod<
    [string, string, string, LockEntryStatus],
    Result_1
  >,
  'updatePpeInventory' : ActorMethod<
    [string, string, bigint, bigint],
    Result_1
  >,
  'verifyCapa2' : ActorMethod<[string, string, boolean, string], Result_1>,
  'whoAmI' : ActorMethod<[string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];